/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * analisisvarianza.java
 *
 * Created on 23-nov-2009, 16:29:50
 */

package anova;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samuel Menéndez
 */
public class analisisvarianza extends javax.swing.JFrame {

    DefaultTableModel modelo=new DefaultTableModel();
    Tablaf obj=new Tablaf();
    Object[] v={};
    double[] nmuestras;
    double[] mediamuestral;
    double[] varianzas;
    int contador=4;
    double sum=0;
    double s=0;
    int nmuestra=0;
    int ntotal=0;
    double mdem=0;
    double mde=0;
    String datos=" ";
    String datosvarianza=" ";
    double ssb=0;
    double vvarianza=0;
    double vv=0;
    double jt=0;
    double num;
    double ssw=0;
    double fcal;
    double ftab;
    double ftp;
    double fcp;
    int alfa;
    int con=0;
    int con2;
    int glnp=0;
    int gldp=0;
    String valor;
    String hipotesisnula=" ";
    String mu="µ";
    String hipotesisalt=" ";
    boolean vector=false;
    


    

    /** Creates new form analisisvarianza */
    public analisisvarianza() {
        
        initComponents();
        obtenertabla.setEnabled(false);
        Obtenervari.setEnabled(false);
        obtener.setEnabled(false);
        obtenertabla.setEnabled(false);
        quitfila.setEnabled(false);
        modelo.addColumn("Muestra 1");
        modelo.addColumn("Muestra 2");
        modelo.addColumn("Muestra 3");
        tabla.setModel(modelo);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        agremuestra = new javax.swing.JButton();
        agrefila = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        quitfila = new javax.swing.JButton();
        ok = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        mdeme = new javax.swing.JTextField();
        obtener = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        Obtenervari = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ho = new javax.swing.JTextField();
        hi = new javax.swing.JTextField();
        decision = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtssb = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtssw = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtmsb = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtmsw = new javax.swing.JTextField();
        obtenertabla = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        fc = new javax.swing.JTextField();
        gln = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        gld = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ft = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        k = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(150, 150, 150));
        jPanel1.setName("ANALISIS VARIANZA"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(150, 150, 150));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Insertar muestras"));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Muestra 1", "Muestra 2", "Muestra 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        agremuestra.setText("Agregar Muestra");
        agremuestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agremuestraActionPerformed(evt);
            }
        });

        agrefila.setText("Agregar Fila");
        agrefila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agrefilaActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(255, 255, 51));
        jLabel14.setText("Alfa");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.01", "0.05" }));

        quitfila.setText("Quitar Fila");
        quitfila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitfilaActionPerformed(evt);
            }
        });

        ok.setText("Ok");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(ok, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(quitfila, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agrefila, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agremuestra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(ok))
                        .addGap(18, 18, 18)
                        .addComponent(agremuestra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agrefila)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quitfila)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(150, 150, 150));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Medias"));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setText("Media de medias");

        mdeme.setColumns(10);

        obtener.setText("Obtener");
        obtener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtenerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(mdeme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(obtener)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(mdeme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(obtener)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(150, 150, 150));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Varianzas"));
        jPanel4.setForeground(new java.awt.Color(255, 255, 51));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        Obtenervari.setText("Obtener");
        Obtenervari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObtenervariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(Obtenervari)
                        .addGap(83, 83, 83))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Obtenervari)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(150, 150, 150));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("Ho");

        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Hi");

        ho.setColumns(15);

        hi.setColumns(15);

        decision.setColumns(15);
        decision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decisionActionPerformed(evt);
            }
        });

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(decision)
                    .addComponent(ho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(hi, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(ho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(hi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(decision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(150, 150, 150));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos tabla generalizada"));

        jLabel9.setForeground(new java.awt.Color(255, 255, 51));
        jLabel9.setText("SSB");

        txtssb.setColumns(8);

        jLabel10.setForeground(new java.awt.Color(255, 255, 51));
        jLabel10.setText("SSW");

        txtssw.setColumns(8);

        jLabel11.setForeground(new java.awt.Color(255, 255, 51));
        jLabel11.setText("MSB");

        txtmsb.setColumns(8);

        jLabel12.setForeground(new java.awt.Color(255, 255, 51));
        jLabel12.setText("MSW");

        txtmsw.setColumns(8);

        obtenertabla.setText("Obtener");
        obtenertabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtenertablaActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 255, 51));
        jLabel13.setText("Fc");

        fc.setColumns(8);

        gln.setColumns(10);

        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("gln");

        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("gld");

        gld.setColumns(10);

        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("Ft");

        ft.setColumns(5);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtssb, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(txtssw, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(fc, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(gln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(gld))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(obtenertabla, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                .addGap(78, 78, 78)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(ft, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmsw)
                            .addComponent(txtmsb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(135, 135, 135))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtssb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtssw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(gln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(gld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtmsb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtmsw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obtenertabla)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("K");

        k.setColumns(10);

        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("N");

        n.setColumns(10);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(n, 0, 0, Short.MAX_VALUE)
                                    .addComponent(k, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void obtenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtenerActionPerformed

        
        if(vector==false){
        nmuestras=new double[modelo.getColumnCount()];
        mediamuestral=new double[modelo.getColumnCount()];
        varianzas=new double[modelo.getColumnCount()];
        vector=true;
        }
        sum=0;
        nmuestra=0;
        s=0;
        media();
               
}//GEN-LAST:event_obtenerActionPerformed

    private void agremuestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agremuestraActionPerformed
    modelo.addColumn("Muestra "+contador);
    contador++;
}//GEN-LAST:event_agremuestraActionPerformed

    private void agrefilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agrefilaActionPerformed
    modelo.addRow(v);
    quitfila.setEnabled(true);
    
}//GEN-LAST:event_agrefilaActionPerformed

    private void obtenertablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtenertablaActionPerformed

        gln.setText(String.valueOf(modelo.getColumnCount()-1));
        gld.setText(String.valueOf(ntotal-modelo.getColumnCount()));
        ssbymsb();
        sswymsw();
        fc.setText(String.format("%.2f",((ssb)/(modelo.getColumnCount()-1))/((ssw)/(ntotal-modelo.getColumnCount()))));
        obtenertabla.setEnabled(false);
        alfa=jComboBox1.getSelectedIndex();
        System.out.println(alfa);
        glnp=modelo.getColumnCount();
        gldp=modelo.getRowCount();

        if((glnp>10)||(gldp>25)){
        ft.setText(JOptionPane.showInputDialog("Introduzca el valor de Ft"));
        fcal=((ssb)/(modelo.getColumnCount()-1))/((ssw)/(ntotal-modelo.getColumnCount()));
        ftp=Double.parseDouble(ft.getText());
        fcp=((ssb)/(modelo.getColumnCount()-1))/((ssw)/(ntotal-modelo.getColumnCount()));
        if(fcp<ftp){
        decision.setText("Fc<Ft");
        jTextArea3.setText("SE CONCLUE QUE LAS MEDIA SON IGUALES");
        }
        else{
        decision.setText("Fc>Ft");
        jTextArea3.setText("SE CONCLUE QUE LAS MEDIAS NO SON IGUALES");
        }
        }else{

        if(alfa==0){
        obtenervalortablauno();
        fcal=((ssb)/(modelo.getColumnCount()-1))/((ssw)/(ntotal-modelo.getColumnCount()));
        ftab=obj.ftuno;
        ft.setText(String.format("%.2f", obj.ftuno));
        if(fcal<ftab){
        decision.setText("Fc<Ft");
        jTextArea3.setText("Se conclue que las medias son iguales");
        }
        else{
        decision.setText("Fc>Ft");
        jTextArea3.setText("Se conclue que las medias no son iguales");
        }
        }

        if(alfa==1){
        obtenervalortablacinco();
        fcal=((ssb)/(modelo.getColumnCount()-1))/((ssw)/(ntotal-modelo.getColumnCount()));
        ftab=obj.ftcinco;
        ft.setText(String.format("%.2f", obj.ftcinco));
        if(fcal<ftab){
        decision.setText("Fc<Ft");
        jTextArea3.setText("Se conclue que las medias son iguales");
        }
        else{
        decision.setText("Fc>Ft");
        jTextArea3.setText("Se conclue que las medias no son iguales");
        }
        }
        }

    }//GEN-LAST:event_obtenertablaActionPerformed

    private void ObtenervariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObtenervariActionPerformed
        varianza();
        k.setText(String.valueOf(modelo.getColumnCount()));
        n.setText(String.valueOf(ntotal));
}//GEN-LAST:event_ObtenervariActionPerformed

    private void decisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decisionActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_decisionActionPerformed

    private void quitfilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitfilaActionPerformed
        try{
        modelo.removeRow(tabla.getSelectedRow());}
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "No hay ninguna fila seleccionada");
        }
}//GEN-LAST:event_quitfilaActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
quitfila.setEnabled(false);
obtener.setEnabled(true);
agrefila.setEnabled(false);
agremuestra.setEnabled(false);
    }//GEN-LAST:event_okActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new analisisvarianza().setVisible(true);
            }
        });
    }

    public void media(){

        int filas=modelo.getRowCount();
        String pase=(String)modelo.getValueAt(0, 0);

if(pase!=null){

        for (int j = 0; j <modelo.getColumnCount(); j++) {
        if(j==modelo.getColumnCount()-1){
        obtener.setEnabled(false);
        }
        for (int i = 0; i <filas; i++) {
        String f=(String)modelo.getValueAt(i, j);
        if(f!=null){
        s=Double.parseDouble(f);
        sum=sum+s;
        nmuestra++;
        }
        }
        sum=sum/nmuestra;
        ntotal=ntotal+nmuestra;
        nmuestras[j]=nmuestra;
        mediamuestral[j]=sum;
        datos=datos+"Media "+(j+1)+" : "+String.format("%.2f",sum)+"\n";
        sum=0;
        nmuestra=0;
        if(j==modelo.getColumnCount()-1){
        mediademedias();
        }
        
        
        jTextArea1.setText(datos);
        Obtenervari.setEnabled(true);
        }
          
    }
else{
JOptionPane.showMessageDialog(null, "No hay datos que calcular");
}
    }


    public void mediademedias(){

        for (int i = 0; i <modelo.getColumnCount(); i++) {
            for (int j = 0; j <modelo.getRowCount(); j++) {
            String m=(String)modelo.getValueAt(j, i);
            if(m!=null){
            mde=Double.parseDouble(m);
            mdem=mdem+mde;
            }

            }

        }
        mdem=mdem/ntotal;
        mdeme.setText(String.format("%.2f",(mdem)));
    }

    public void ssbymsb(){

        int poblacion=modelo.getColumnCount();
        for (int i = 0; i <poblacion ; i++) {
        double h=mediamuestral[i]-mdem;
        ssb=ssb+((nmuestras[i])*(Math.pow(h, 2)));
        }

        txtssb.setText(String.format("%.2f",ssb));
        txtmsb.setText(String.format("%.2f",ssb/(modelo.getColumnCount()-1)));
   }

    public  void varianza(){
    
        int filas=modelo.getRowCount();
        
        for (int a = 0; a < modelo.getColumnCount(); a++) {
           for (int i = 0; i < filas; i++) {
        valor=(String)modelo.getValueAt(i, a);
        if(valor!=null){
        vv=(Double.parseDouble(valor))-(mediamuestral[a]);
        vvarianza=vvarianza+Math.pow(vv, 2);
        }
        }
        varianzas[a]=vvarianza/(nmuestras[a]-1);
        datosvarianza=datosvarianza+"Varianza "+(a+1)+": "+String.format("%.2f",(vvarianza)/(nmuestras[a]-1))+"\n";
        vv=0;
        vvarianza=0;
        }
        jTextArea2.setText(datosvarianza);
        Obtenervari.setEnabled(false);
        obtenertabla.setEnabled(true);
        hipotesis();
        
        }
        
   

    public void sswymsw(){

        for (int i = 0; i < modelo.getColumnCount(); i++) {
            ssw=ssw+((nmuestras[i]-1)*varianzas[i]);
        }

        txtssw.setText(String.format("%.2f", ssw));
        txtmsw.setText(String.format("%.2f", ((ssw)/(ntotal-modelo.getColumnCount()))));


    }

    public void hipotesis(){

        for (int i = 0; i < modelo.getColumnCount(); i++) {
         if(i>=modelo.getColumnCount()-1){
         hipotesisnula=hipotesisnula+"µ"+(modelo.getColumnCount());
         }
         else{
         hipotesisnula=hipotesisnula+"µ"+(i+1)+"=";
        }
        }

        for (int i = 0; i < modelo.getColumnCount(); i++) {
         if(i>=modelo.getColumnCount()-1){
         hipotesisalt=hipotesisalt+"µ"+(modelo.getColumnCount());
         }
         else{
         hipotesisalt=hipotesisalt+"µ"+(i+1)+"!=";
        }
        }

        ho.setText(hipotesisnula);
        hi.setText(hipotesisalt);

    }

    public void obtenervalortablacinco(){

        int glntc=modelo.getColumnCount()-1;
        int gldtc=ntotal-modelo.getColumnCount();
        obj.tablafcinco(gldtc, glntc);
    }

    public void obtenervalortablauno(){

        int glntu=modelo.getColumnCount()-1;
        int gldtu=ntotal-modelo.getColumnCount()-1;
        obj.tablafuno(gldtu, glntu);
    }



    

       
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Obtenervari;
    private javax.swing.JButton agrefila;
    private javax.swing.JButton agremuestra;
    private javax.swing.JTextField decision;
    private javax.swing.JTextField fc;
    private javax.swing.JTextField ft;
    private javax.swing.JTextField gld;
    private javax.swing.JTextField gln;
    private javax.swing.JTextField hi;
    private javax.swing.JTextField ho;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField k;
    private javax.swing.JTextField mdeme;
    private javax.swing.JTextField n;
    private javax.swing.JButton obtener;
    private javax.swing.JButton obtenertabla;
    private javax.swing.JButton ok;
    private javax.swing.JButton quitfila;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtmsb;
    private javax.swing.JTextField txtmsw;
    private javax.swing.JTextField txtssb;
    private javax.swing.JTextField txtssw;
    // End of variables declaration//GEN-END:variables

}
