/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Cargar_Parcial.java
 *
 * Created on Nov 24, 2010, 12:32:15 AM
 */
package formularios;

import clases.Generador_Reportes;
import clases.Operaciones;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author greg
 */
public class Cargar_Parcial extends javax.swing.JFrame {

    Operaciones op = new Operaciones();
    Generador_Reportes jasper;

    /** Creates new form Cargar_Parcial */
    public Cargar_Parcial() {
        initComponents();
        jasper = new Generador_Reportes();
        btnGenerarParcial.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdParciales = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        txtCod = new javax.swing.JTextField();
        txtFec = new javax.swing.JTextField();
        txtMater = new javax.swing.JTextField();
        txtDep = new javax.swing.JTextField();
        txtDoc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnModiEncabezado = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNompar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGT = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jccNuevaFechaUno = new org.freixas.jcalendar.JCalendarCombo();
        jPanel5 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        txtPregun = new javax.swing.JTextField();
        txtREsp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jdParcialMulti = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        txtCod1 = new javax.swing.JTextField();
        txtFec1 = new javax.swing.JTextField();
        txtMater1 = new javax.swing.JTextField();
        txtGT1 = new javax.swing.JTextField();
        txtDep1 = new javax.swing.JTextField();
        txtNompar1 = new javax.swing.JTextField();
        txtDoc1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTipo1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btmModiMulti = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jccNuevaFechaDos = new org.freixas.jcalendar.JCalendarCombo();
        jPanel7 = new javax.swing.JPanel();
        txtPregunMulti = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btnModiPregunMulti = new javax.swing.JButton();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        txtResE = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtResD = new javax.swing.JTextField();
        txtResC = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtResB = new javax.swing.JTextField();
        txtResA = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCargar = new javax.swing.JButton();
        txtmaterias = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcTipos = new javax.swing.JComboBox();
        jbEliminarParcial = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnGenerarParcial = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListar = new javax.swing.JTable();

        jdParciales.setTitle("Parciales");
        jdParciales.setMinimumSize(new java.awt.Dimension(719, 297));
        jdParciales.setModal(true);
        jdParciales.setResizable(false);
        jdParciales.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jdParcialesWindowClosing(evt);
            }
        });
        jdParciales.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)), "Encabezado Parcial"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCod.setEnabled(false);
        txtCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodKeyPressed(evt);
            }
        });
        jPanel4.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 21, 49, -1));

        txtFec.setEnabled(false);
        jPanel4.add(txtFec, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 110, -1));

        txtMater.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMaterKeyTyped(evt);
            }
        });
        jPanel4.add(txtMater, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 220, -1));

        txtDep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDepKeyTyped(evt);
            }
        });
        jPanel4.add(txtDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 220, -1));

        txtDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDocKeyTyped(evt);
            }
        });
        jPanel4.add(txtDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 220, -1));

        jLabel2.setText("Codigo:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel4.setText("Fecha Parcial:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel5.setText("Materia:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel7.setText("Departamento:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel8.setText("Docente:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txtTipo.setEnabled(false);
        jPanel4.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 120, -1));

        jLabel12.setText("Tipo Parcial:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        btnModiEncabezado.setText("Modificar");
        btnModiEncabezado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModiEncabezadoActionPerformed(evt);
            }
        });
        jPanel4.add(btnModiEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 90, -1));

        jLabel3.setText("Nombre Parcial:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtNompar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomparKeyTyped(evt);
            }
        });
        jPanel4.add(txtNompar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 140, -1));

        jLabel6.setText("Grupo Teorico:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txtGT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGTKeyTyped(evt);
            }
        });
        jPanel4.add(txtGT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 120, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/escribir-comentario.gif"))); // NOI18N
        jLabel32.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        jccNuevaFechaUno.addDateListener(new org.freixas.jcalendar.DateListener() {
            public void dateChanged(org.freixas.jcalendar.DateEvent evt) {
                jccNuevaFechaUnoDateChanged(evt);
            }
        });
        jPanel4.add(jccNuevaFechaUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 30, -1));

        jdParciales.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 350, 260));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)), "Preguntas y Respuestas"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jPanel5.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 40, -1));
        jPanel5.add(txtPregun, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 220, -1));
        jPanel5.add(txtREsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 220, -1));

        jLabel9.setText("Pregunta:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel10.setText("Moverse por las Preguntas:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 80, -1));

        jLabel28.setText("Respuesta:");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/escribir73.gif"))); // NOI18N
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 50, 40));

        jdParciales.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 330, 260));

        jdParcialMulti.setTitle("Parcial Multi");
        jdParcialMulti.setMinimumSize(new java.awt.Dimension(822, 293));
        jdParcialMulti.setResizable(false);
        jdParcialMulti.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)), "Encabezado Parcial"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCod1.setEnabled(false);
        jPanel6.add(txtCod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 49, -1));

        txtFec1.setEnabled(false);
        jPanel6.add(txtFec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 110, -1));

        txtMater1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMater1KeyTyped(evt);
            }
        });
        jPanel6.add(txtMater1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 260, -1));

        txtGT1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGT1KeyTyped(evt);
            }
        });
        jPanel6.add(txtGT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 50, -1));

        txtDep1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDep1KeyTyped(evt);
            }
        });
        jPanel6.add(txtDep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 260, -1));

        txtNompar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNompar1KeyTyped(evt);
            }
        });
        jPanel6.add(txtNompar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 130, -1));

        txtDoc1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDoc1KeyTyped(evt);
            }
        });
        jPanel6.add(txtDoc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 260, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/escribir-comentario.gif"))); // NOI18N
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLabel14.setText("Nombre Parcial:");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel15.setText("Fecha Parcial:");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel16.setText("Materia:");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel17.setText("Grupo Teorico:");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel18.setText("Departamento:");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel19.setText("Docente:");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 50, -1));

        txtTipo1.setEnabled(false);
        jPanel6.add(txtTipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 120, -1));

        jLabel20.setText("Tipo Parcial:");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, 20));

        btmModiMulti.setText("Modificar");
        btmModiMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmModiMultiActionPerformed(evt);
            }
        });
        jPanel6.add(btmModiMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 90, -1));

        jLabel29.setText("Codigo:");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jccNuevaFechaDos.addDateListener(new org.freixas.jcalendar.DateListener() {
            public void dateChanged(org.freixas.jcalendar.DateEvent evt) {
                jccNuevaFechaDosDateChanged(evt);
            }
        });
        jPanel6.add(jccNuevaFechaDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 30, -1));

        jdParcialMulti.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 260));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)), "Preguntas"));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(txtPregunMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 290, -1));

        jLabel21.setText("Pregunta:");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/escribir73.gif"))); // NOI18N
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 50, 40));

        btnModiPregunMulti.setText("Modificar");
        btnModiPregunMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModiPregunMultiActionPerformed(evt);
            }
        });
        jPanel7.add(btnModiPregunMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 90, -1));

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));
        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });
        jPanel7.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 40, 20));

        jLabel30.setText("Recorrer preguntas:");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 29, 110, 20));

        jdParcialMulti.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 400, 90));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)), "Respuestas"));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(txtResE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 324, -1));

        jLabel26.setText("e)");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel25.setText("d)");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        jPanel8.add(txtResD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 324, -1));
        jPanel8.add(txtResC, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 325, -1));

        jLabel24.setText("c)");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel23.setText("b)");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        jPanel8.add(txtResB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 324, -1));
        jPanel8.add(txtResA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 324, -1));

        jLabel22.setText("a)");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jdParcialMulti.getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 400, 170));

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)), "Seleccione el Parcial a Cargar"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 86, -1));

        txtmaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmateriasActionPerformed(evt);
            }
        });
        txtmaterias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmateriasKeyPressed(evt);
            }
        });
        jPanel1.add(txtmaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 153, -1));

        jLabel1.setText("Nombre Materia:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 70, -1, -1));

        jLabel11.setText("Tipo de Parcial:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 36, -1, -1));

        jcTipos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Complementar", "Apareamiento", "Falso o Verdadero", "Opcion Multiple", "Parentesis" }));
        jPanel1.add(jcTipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 154, -1));

        jbEliminarParcial.setText("Eliminar");
        jbEliminarParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarParcialActionPerformed(evt);
            }
        });
        jPanel1.add(jbEliminarParcial, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 86, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)), "Generar parcial"));

        btnGenerarParcial.setText("Generar");
        btnGenerarParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarParcialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnGenerarParcial)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGenerarParcial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 560, 110));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)), "Parciales Guardados"));

        jtListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtListar);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 137, 560, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // TODO add your handling code here:
        if (jcTipos.getSelectedIndex() == 3) {
            jdParcialMulti.setLocationRelativeTo(null);
            jdParcialMulti.setVisible(true);
            txtCod1.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 0));
            txtNompar1.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 1));
            txtFec1.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 2));
            txtMater1.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 3));
            txtGT1.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 4));
            txtDep1.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 5));
            txtDoc1.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 6));
            txtTipo1.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 7));
        } else if (jcTipos.getSelectedIndex() == 1) {
            jdParciales.setLocationRelativeTo(null);
            jdParciales.setVisible(true);
            txtCod.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 0));
            txtNompar.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 1));
            txtFec.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 2));
            txtMater.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 3));
            txtGT.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 4));
            txtDep.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 5));
            txtDoc.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 6));
            txtTipo.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 7));
        } else {
            jdParciales.setLocationRelativeTo(null);
            jdParciales.setVisible(true);
            txtCod.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 0));
            txtNompar.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 1));
            txtFec.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 2));
            txtMater.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 3));
            txtGT.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 4));
            txtDep.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 5));
            txtDoc.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 6));
            txtTipo.setText((String) jtListar.getValueAt(jtListar.getSelectedRow(), 7));
        }
        txtmaterias.setText("");
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnGenerarParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarParcialActionPerformed
        // TODO add your handling code here:
        String urlimagen = null;
        if (jcTipos.getSelectedIndex() == 0) {
            String cod = (String) jtListar.getValueAt(jtListar.getSelectedRow(), 0);
            System.out.println("valor del codigo " + cod);
            String direccion = System.getProperty("user.dir") + "\\src\\plantillas\\Complementario.jasper";
            urlimagen = System.getProperty("user.dir") + "\\src\\imagenes\\minerva.jpg";
            jasper.runReporte(cod, direccion, urlimagen);
        } else if (jcTipos.getSelectedIndex() == 1) {
            String cod = (String) jtListar.getValueAt(jtListar.getSelectedRow(), 0);
            System.out.println("valor del codigo " + cod);
            String direccion = System.getProperty("user.dir") + "\\src\\plantillas\\Apareamiento.jasper";
            urlimagen = System.getProperty("user.dir") + "\\src\\imagenes\\minerva.jpg";
            jasper.runReporte(cod, direccion, urlimagen);
        } else if (jcTipos.getSelectedIndex() == 2) {
            String cod = (String) jtListar.getValueAt(jtListar.getSelectedRow(), 0);
            System.out.println("valor del codigo " + cod);
            String direccion = System.getProperty("user.dir") + "\\src\\plantillas\\FalsoVerdadero.jasper";
            urlimagen = System.getProperty("user.dir") + "\\src\\imagenes\\minerva.jpg";
            jasper.runReporte(cod, direccion, urlimagen);
        } else if (jcTipos.getSelectedIndex() == 3) {
            String cod = (String) jtListar.getValueAt(jtListar.getSelectedRow(), 0);
            System.out.println("valor del codigo " + cod);
            String direccion = System.getProperty("user.dir") + "\\src\\plantillas\\opcionMultiple.jasper";
            urlimagen = System.getProperty("user.dir") + "\\src\\imagenes\\minerva.jpg";
            jasper.runReporte(cod, direccion, urlimagen);
        } else if (jcTipos.getSelectedIndex() == 4) {
            String cod = (String) jtListar.getValueAt(jtListar.getSelectedRow(), 0);
            System.out.println("valor del codigo " + cod);
            String direccion = System.getProperty("user.dir") + "\\src\\plantillas\\parentesis.jasper";
            urlimagen = System.getProperty("user.dir") + "\\src\\imagenes\\minerva.jpg";
            jasper.runReporte(direccion, direccion, urlimagen);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor seleccione un tipo de parcial para la busqueda");
        }
        txtmaterias.setText("");
    }//GEN-LAST:event_btnGenerarParcialActionPerformed

    private void txtmateriasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmateriasKeyPressed
        String tipo = jcTipos.getSelectedItem().toString();
        this.jtListar.setModel(op.buscar_parciales(tipo, this.txtmaterias.getText()));
        btnGenerarParcial.setEnabled(true);
        if(btnGenerarParcial.getText() == null){
            btnGenerarParcial.setEnabled(false);
        }
    }//GEN-LAST:event_txtmateriasKeyPressed

    private void txtCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodKeyPressed
        try {
            // TODO add your handling code here:
            String cod = txtCod.getText();
            op.enlazar(cod);
        } catch (SQLException ex) {
            System.out.println("error: " + ex.getMessage());
        }
    }//GEN-LAST:event_txtCodKeyPressed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        try {
            // TODO add your handling code here:
            String num = jSpinner1.getValue() + ":";
            int cod = Integer.parseInt(txtCod.getText());
            op.enlazarParciales(num, cod);
            txtPregun.setText(op.pregun);
            txtREsp.setText(op.respues);
            System.out.println("pregunta:" + op.pregun + "respuesta: " + op.respues);
        } catch (SQLException ex) {
            Logger.getLogger(Cargar_Parcial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jSpinner1StateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int close = JOptionPane.showConfirmDialog(this, "Desea Cerrar esta aplicacion \n y volver al inicio", "Cerrar", JOptionPane.YES_NO_OPTION);
        if (close == 0) {
            this.hide();
            Principal obj = new Principal();
            obj.setVisible(true);
            obj.setLocationRelativeTo(null);
        } else {
            this.show();
        }
    }//GEN-LAST:event_formWindowClosing

    private void jdParcialesWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jdParcialesWindowClosing
        // TODO add your handling code here:
        txtCod.setText("");
        txtNompar.setText("");
        txtFec.setText("");
        txtMater.setText("");
        txtGT.setText("");
        txtDep.setText("");
        txtDoc.setText("");
        txtTipo.setText("");
        txtPregun.setText("");
        txtREsp.setText("");
    }//GEN-LAST:event_jdParcialesWindowClosing

    private void btnModiEncabezadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModiEncabezadoActionPerformed
        try {
            // TODO add your handling code here:
            String nom, fec, mat, gt, dep, doc;
            int cod;
            cod = Integer.parseInt(txtCod.getText());
            nom = txtNompar.getText();
            fec = txtFec.getText();
            mat = txtMater.getText();
            gt = txtGT.getText();
            dep = txtDep.getText();
            doc = txtDoc.getText();
            op.actualizarEncabezado(cod, nom, fec, mat, gt, dep, doc);
        } catch (SQLException ex) {
            System.out.println("Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnModiEncabezadoActionPerformed

    private void btmModiMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmModiMultiActionPerformed
        // TODO add your handling code here:
        try {
            String nom, fec, mat, gt, dep, doc;
            int cod;
            cod = Integer.parseInt(txtCod1.getText());
            nom = txtNompar1.getText();
            fec = txtFec1.getText();
            mat = txtMater1.getText();
            gt = txtGT1.getText();
            dep = txtDep1.getText();
            doc = txtDoc1.getText();
            op.actualizarEncabezado(cod, nom, fec, mat, gt, dep, doc);
        } catch (SQLException ex) {
            System.out.println("Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btmModiMultiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String num = jSpinner1.getValue().toString() + ":";
            String pre = txtPregun.getText();
            String rep = txtREsp.getText();
            op.actualizar(num, rep, pre);
        } catch (SQLException ex) {
            System.out.println("Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnModiPregunMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModiPregunMultiActionPerformed
        String num, pre, resp1, resp2, resp3, resp4, resp5;
        num = jSpinner2.getValue().toString() + ":";
        pre = txtPregun.getText();
        resp1 = txtResA.getText();
        resp2 = txtResB.getText();
        resp3 = txtResC.getText();
        resp4 = txtResD.getText();
        resp5 = txtResE.getText();
        try {
            op.actualizarOpcionMultiple(num, pre, resp1, resp2, resp3, resp4, resp5);
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_btnModiPregunMultiActionPerformed

    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        // TODO add your handling code here:
        String num = jSpinner2.getValue() + ":";
        int cod = Integer.parseInt(txtCod1.getText());
        op.enlazarOpcnionMult(num, cod);
        txtPregunMulti.setText(op.pregun);
        txtResA.setText(op.rep1);
        txtResB.setText(op.rep2);
        txtResC.setText(op.rep3);
        txtResD.setText(op.rep4);
        txtResE.setText(op.rep5);
    }//GEN-LAST:event_jSpinner2StateChanged

    private void jbEliminarParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarParcialActionPerformed
        // TODO add your handling code here:
        String codi = (String) jtListar.getValueAt(jtListar.getSelectedRow(), 0);
        int cod = Integer.parseInt(codi);
        op.eliminar(cod);
        this.jtListar.setModel(op.buscar_parciales(codi, codi));
        txtmaterias.setText("");
    }//GEN-LAST:event_jbEliminarParcialActionPerformed

    private void jccNuevaFechaUnoDateChanged(org.freixas.jcalendar.DateEvent evt) {//GEN-FIRST:event_jccNuevaFechaUnoDateChanged
        // TODO add your handling code here:
        SimpleDateFormat obj = new SimpleDateFormat("yyyy-MM-dd");
        txtFec.setText(obj.format(jccNuevaFechaUno.getDate()));
    }//GEN-LAST:event_jccNuevaFechaUnoDateChanged

    private void jccNuevaFechaDosDateChanged(org.freixas.jcalendar.DateEvent evt) {//GEN-FIRST:event_jccNuevaFechaDosDateChanged
        // TODO add your handling code here:
        SimpleDateFormat obj = new SimpleDateFormat("yyyy-MM-dd");
        txtFec1.setText(obj.format(jccNuevaFechaUno.getDate()));
    }//GEN-LAST:event_jccNuevaFechaDosDateChanged

    private void txtNompar1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNompar1KeyTyped
        // TODO add your handling code here:
                    if (!Character.isLetter(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar())) {
                evt.consume();
            }
    }//GEN-LAST:event_txtNompar1KeyTyped

    private void txtMater1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMater1KeyTyped
        // TODO add your handling code here:
                    if (!Character.isLetter(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar())) {
                evt.consume();
            }
    }//GEN-LAST:event_txtMater1KeyTyped

    private void txtDep1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDep1KeyTyped
        // TODO add your handling code here:
                    if (!Character.isLetter(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar())) {
                evt.consume();
            }
    }//GEN-LAST:event_txtDep1KeyTyped

    private void txtDoc1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDoc1KeyTyped
        // TODO add your handling code here:
                    if (!Character.isLetter(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar())) {
                evt.consume();
            }
    }//GEN-LAST:event_txtDoc1KeyTyped

    private void txtGT1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGT1KeyTyped
        // TODO add your handling code here:
                    if (!Character.isDigit(evt.getKeyChar())) {
                evt.consume();
            }
    }//GEN-LAST:event_txtGT1KeyTyped

    private void txtGTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGTKeyTyped
        // TODO add your handling code here:
          if (!Character.isDigit(evt.getKeyChar())) {
                evt.consume();
            }
    }//GEN-LAST:event_txtGTKeyTyped

    private void txtDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocKeyTyped
        // TODO add your handling code here:
          if (!Character.isLetter(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar())) {
                evt.consume();
            }
    }//GEN-LAST:event_txtDocKeyTyped

    private void txtDepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDepKeyTyped
        // TODO add your handling code here:
          if (!Character.isLetter(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar())) {
                evt.consume();
            }
    }//GEN-LAST:event_txtDepKeyTyped

    private void txtMaterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaterKeyTyped
        // TODO add your handling code here:
          if (!Character.isLetter(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar())) {
                evt.consume();
            }
    }//GEN-LAST:event_txtMaterKeyTyped

    private void txtNomparKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomparKeyTyped
        // TODO add your handling code here:
          if (!Character.isLetter(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar())) {
                evt.consume();
            }
    }//GEN-LAST:event_txtNomparKeyTyped

    private void txtmateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmateriasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtmateriasActionPerformed

    /**
     * Metodo principal de la clase
     * Cargar_Parcial.java
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Cargar_Parcial obj = new Cargar_Parcial();
                obj.setLocationRelativeTo(null);
                obj.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmModiMulti;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnGenerarParcial;
    private javax.swing.JButton btnModiEncabezado;
    private javax.swing.JButton btnModiPregunMulti;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JButton jbEliminarParcial;
    private javax.swing.JComboBox jcTipos;
    private org.freixas.jcalendar.JCalendarCombo jccNuevaFechaDos;
    private org.freixas.jcalendar.JCalendarCombo jccNuevaFechaUno;
    private javax.swing.JDialog jdParcialMulti;
    private javax.swing.JDialog jdParciales;
    private javax.swing.JTable jtListar;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtCod1;
    private javax.swing.JTextField txtDep;
    private javax.swing.JTextField txtDep1;
    private javax.swing.JTextField txtDoc;
    private javax.swing.JTextField txtDoc1;
    private javax.swing.JTextField txtFec;
    private javax.swing.JTextField txtFec1;
    private javax.swing.JTextField txtGT;
    private javax.swing.JTextField txtGT1;
    private javax.swing.JTextField txtMater;
    private javax.swing.JTextField txtMater1;
    private javax.swing.JTextField txtNompar;
    private javax.swing.JTextField txtNompar1;
    private javax.swing.JTextField txtPregun;
    private javax.swing.JTextField txtPregunMulti;
    private javax.swing.JTextField txtREsp;
    private javax.swing.JTextField txtResA;
    private javax.swing.JTextField txtResB;
    private javax.swing.JTextField txtResC;
    private javax.swing.JTextField txtResD;
    private javax.swing.JTextField txtResE;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtTipo1;
    private javax.swing.JTextField txtmaterias;
    // End of variables declaration//GEN-END:variables
}
