package playlistxml;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
/**
 * @web http://jc-mouse.blogspot.com/
 * @author Mouse
 */

/* OBJETO PARA COLOCAR LOS DATOS DEL  ARCHIVO XML POR CANCION */
public class song extends javax.swing.JPanel {
    private String Titulo="";
    private String Artista="";
    private String Album="";
    private String Location="";
    private String preview_dir="";
    
    private boolean selecionado = false;
    
    /** Creates new form song */
    public song() {
        initComponents();       
        Dimension d = new Dimension(400,100);
        //this.setPreferredSize(d);
        this.setSize(d);        
        //se cambia de cursor default por otro, el de la "manito"
        preview.setCursor(new Cursor(Cursor.HAND_CURSOR));               
        //this.repaint();
    }
    
    
    public void setTitulo(String t){
        this.Titulo = t;
        jtTitle.setText("Titulo: " + this.Titulo);
    }
    
    public String getTitulo(){
        return this.Titulo;
    }
    
    public void setArtista(String a){
        this.Artista = a;
        jtArtista.setText("Artista: " + this.Artista);
    }
    
    public String getArtista(){
        return this.Artista;
    }
    
    public void setAlbum(String a){
        this.Album=a;
        jtAlbum.setText("Album: " + this.Album);
    }
    
    public String getAlbum(){
           return this.Album;
    }   
    
    public void setLocation(String l){
        this.Location=l;
        jtLocation1.setText("Location: " + this.Location);
    }
    
    public String getLoaction(){
        return this.Location;
    }
    
    public void setSeleccion(boolean b){
        this.selecionado=b;
    }
    
    public Boolean getSeleccion(){
        return this.selecionado;
    }
    
    public void setPreview(String p){
        if(p.length()>0){
            this.preview_dir=p;        
        }else{
            this.preview_dir="/album/noalbum.jpg";        
        }      
        preview.setIcon(new javax.swing.ImageIcon(getClass().getResource(this.preview_dir)));        
    }
    
    public String getPreview(){
            return this.preview_dir;
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        preview = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtTitle = new javax.swing.JTextField();
        jtArtista = new javax.swing.JTextField();
        jtAlbum = new javax.swing.JTextField();
        jtLocation = new javax.swing.JTextField();
        jtLocation1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        preview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/album/noalbum.jpg"))); // NOI18N
        preview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previewMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(preview, gridBagConstraints);

        add(jPanel1, new java.awt.GridBagConstraints());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jtTitle.setBackground(new java.awt.Color(0, 0, 0));
        jtTitle.setForeground(new java.awt.Color(0, 204, 0));
        jtTitle.setText("Titulo:");
        jtTitle.setBorder(null);
        jtTitle.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 2, 2);
        jPanel2.add(jtTitle, gridBagConstraints);

        jtArtista.setBackground(new java.awt.Color(0, 0, 0));
        jtArtista.setForeground(new java.awt.Color(0, 204, 0));
        jtArtista.setText("Artista:");
        jtArtista.setBorder(null);
        jtArtista.setPreferredSize(new java.awt.Dimension(300, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        jPanel2.add(jtArtista, gridBagConstraints);

        jtAlbum.setBackground(new java.awt.Color(0, 0, 0));
        jtAlbum.setForeground(new java.awt.Color(0, 204, 0));
        jtAlbum.setText("Album:");
        jtAlbum.setBorder(null);
        jtAlbum.setPreferredSize(new java.awt.Dimension(300, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        jPanel2.add(jtAlbum, gridBagConstraints);

        jtLocation.setBackground(new java.awt.Color(0, 0, 0));
        jtLocation.setForeground(new java.awt.Color(0, 204, 0));
        jtLocation.setText("-------------------------------------------------------------------------");
        jtLocation.setBorder(null);
        jtLocation.setPreferredSize(new java.awt.Dimension(300, 14));
        jtLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtLocationActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        jPanel2.add(jtLocation, gridBagConstraints);

        jtLocation1.setBackground(new java.awt.Color(0, 0, 0));
        jtLocation1.setForeground(new java.awt.Color(0, 204, 0));
        jtLocation1.setText("Location:");
        jtLocation1.setBorder(null);
        jtLocation1.setPreferredSize(new java.awt.Dimension(300, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        jPanel2.add(jtLocation1, gridBagConstraints);

        add(jPanel2, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void previewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previewMouseClicked
        for(int i=0; i<this.getParent().getComponentCount();i++){
            ((song)this.getParent().getComponent(i)).jtTitle.setBackground(new Color(0,0,0));             
            ((song)this.getParent().getComponent(i)).setSeleccion(false);                         
        }
        jtTitle.setBackground(new Color(160,10,10));
        setSeleccion(true);                
    }//GEN-LAST:event_previewMouseClicked

    private void jtLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtLocationActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jtAlbum;
    private javax.swing.JTextField jtArtista;
    private javax.swing.JTextField jtLocation;
    private javax.swing.JTextField jtLocation1;
    private javax.swing.JTextField jtTitle;
    private javax.swing.JLabel preview;
    // End of variables declaration//GEN-END:variables
    
}
