package metodosIterativos;


import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * newtonForm.java
 *
 * Created on May 31, 2011, 10:20:45 PM
 */
/**
 *
 * @author jdOrellana
 */
public class newtonForm extends javax.swing.JFrame {

    Newton objNewton;
    DefaultTableModel modeloTabla;

    /** Creates new form newtonForm */
    public newtonForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        modeloTabla = (DefaultTableModel) jTable1.getModel();
        jTable1.setModel(modeloTabla);
    }

    private boolean validarCampos() {
        boolean res = false;
        res = !jTFTolerancia.getText().trim().isEmpty() && !jTFa.getText().trim().isEmpty();
        res = res && !jTFn.getText().trim().isEmpty();
        cmbCalcular.setEnabled(res);
        return res;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTFRaiz = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbCalcular = new javax.swing.JButton();
        jTFTolerancia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFa = new javax.swing.JTextField();
        lblErrores = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTFn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "n", "Xo", "f(Xo)", "f'(Xo)", "X1", "Error", "Convergencia"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTFRaiz.setEditable(false);

        jLabel5.setText("Valor de la raíz:");

        cmbCalcular.setText("Calcular");
        cmbCalcular.setEnabled(false);
        cmbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCalcularActionPerformed(evt);
            }
        });

        jTFTolerancia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFToleranciaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFToleranciaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFToleranciaKeyTyped(evt);
            }
        });

        jLabel4.setText("Tolerancia:");

        jTFa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFaKeyReleased(evt);
            }
        });

        lblErrores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblErrores.setMinimumSize(new java.awt.Dimension(700, 26));

        jLabel2.setText("Valor de Xo:");

        jLabel1.setText("Valor de n:");

        jTFn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFnKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFnKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFnKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel7.setText("NEWTON-RAPHSON");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel6.setText("ERICK STANLEY CRUZ MARTINEZ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTFTolerancia, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTFa, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTFn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addComponent(cmbCalcular))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTFn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCalcular))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTFa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTFTolerancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTFRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCalcularActionPerformed
        try {
            jTFRaiz.setText("");
            objNewton = new Newton(Double.parseDouble(jTFTolerancia.getText()), Integer.parseInt(jTFn.getText()), Double.parseDouble(jTFa.getText()));
            objNewton.setModelo(modeloTabla);

            jTFRaiz.setText(String.format("%.6f", objNewton.calcularRaiz())); //trabajamos con 6 decimales después del punto
            lblErrores.setText("");
        } catch (Exception e) {
            lblErrores.setText(e.toString());
        }
}//GEN-LAST:event_cmbCalcularActionPerformed

    private void jTFToleranciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFToleranciaKeyPressed
        if ((jTFTolerancia.getText().contains(".") && evt.getKeyChar() == '.') && !Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
}//GEN-LAST:event_jTFToleranciaKeyPressed

    private void jTFToleranciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFToleranciaKeyReleased
        validarCampos();
}//GEN-LAST:event_jTFToleranciaKeyReleased

    private void jTFToleranciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFToleranciaKeyTyped
        if ((!Character.isDigit(evt.getKeyChar()) || jTFTolerancia.getText().length() > 15) && jTFTolerancia.getText().contains(".")) {
            evt.consume();
        }
}//GEN-LAST:event_jTFToleranciaKeyTyped

    private void jTFaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFaKeyReleased
        validarCampos();
}//GEN-LAST:event_jTFaKeyReleased

    private void jTFnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFnKeyPressed
        if ((jTFn.getText().contains(".") && evt.getKeyChar() == '.') && !Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
}//GEN-LAST:event_jTFnKeyPressed

    private void jTFnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFnKeyReleased
        validarCampos();
}//GEN-LAST:event_jTFnKeyReleased

    private void jTFnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFnKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) || jTFn.getText().length() > 15) {
            evt.consume();
        }
}//GEN-LAST:event_jTFnKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new newtonForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFRaiz;
    private javax.swing.JTextField jTFTolerancia;
    private javax.swing.JTextField jTFa;
    private javax.swing.JTextField jTFn;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblErrores;
    // End of variables declaration//GEN-END:variables
}
