/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * secForm.java
 *
 * Created on 16-may-2011, 22:47:57
 */

package metodosIterativos;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class secForm extends javax.swing.JFrame {

    Secante objSecante;
    DefaultTableModel modeloTabla;

    /** Creates new form secForm */
    public secForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        modeloTabla = (DefaultTableModel) jTable1.getModel();
        jTable1.setModel(modeloTabla);
    }

    private boolean validarCampos() {
        boolean res = false;
        res = !jTFTolerancia.getText().trim().isEmpty() && !jTFa.getText().trim().isEmpty();
        res = res && !jTFb.getText().trim().isEmpty() && !jTFn.getText().trim().isEmpty();
        cmbCalcular.setEnabled(res);
        return res;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTFa = new javax.swing.JTextField();
        jTFb = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFTolerancia = new javax.swing.JTextField();
        cmbCalcular = new javax.swing.JButton();
        jTFRaiz = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblErrores = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(755, 432));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setText("Valor de a:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 42, 65, 14);

        jTFa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFaKeyReleased(evt);
            }
        });
        getContentPane().add(jTFa);
        jTFa.setBounds(112, 39, 51, 20);

        jTFb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFbKeyReleased(evt);
            }
        });
        getContentPane().add(jTFb);
        jTFb.setBounds(112, 65, 51, 20);

        jLabel3.setText("Valor de b:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 68, 70, 14);

        jLabel4.setText("Tolerancia:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 92, 89, 14);

        jTFTolerancia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFToleranciaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFToleranciaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFToleranciaKeyTyped(evt);
            }
        });
        getContentPane().add(jTFTolerancia);
        jTFTolerancia.setBounds(112, 89, 51, 20);

        cmbCalcular.setText("Calcular");
        cmbCalcular.setEnabled(false);
        cmbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCalcular);
        cmbCalcular.setBounds(190, 90, 90, 23);

        jTFRaiz.setEditable(false);
        getContentPane().add(jTFRaiz);
        jTFRaiz.setBounds(112, 138, 163, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel6.setText("ERICK STANLEY CRUZ MARTINEZ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(309, 129, 300, 32);

        jLabel5.setText("Valor de la raíz:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 141, 98, 14);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "n", "X0", "X1", "f(X0)", "f(X1)", "X2", "f(X2)", "Error", "Convergencia"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 170, 730, 184);

        lblErrores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblErrores.setMinimumSize(new java.awt.Dimension(700, 26));
        getContentPane().add(lblErrores);
        lblErrores.setBounds(10, 372, 730, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel7.setText("SECANTE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(313, 75, 130, 32);

        jTFn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFnKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFnKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFnKeyTyped(evt);
            }
        });
        getContentPane().add(jTFn);
        jTFn.setBounds(110, 10, 50, 20);

        jLabel1.setText("Valor de n:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 14, 82, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFaKeyReleased
        validarCampos();
}//GEN-LAST:event_jTFaKeyReleased

    private void jTFbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFbKeyReleased
        validarCampos();
}//GEN-LAST:event_jTFbKeyReleased

    private void jTFToleranciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFToleranciaKeyPressed
        if ((jTFTolerancia.getText().contains(".") && evt.getKeyChar() == '.') && !Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
}//GEN-LAST:event_jTFToleranciaKeyPressed

    private void jTFToleranciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFToleranciaKeyReleased
        validarCampos();
}//GEN-LAST:event_jTFToleranciaKeyReleased

    private void jTFToleranciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFToleranciaKeyTyped
        if ((!Character.isDigit(evt.getKeyChar()) || jTFTolerancia.getText().length() > 15) && jTFTolerancia.getText().contains(".")) {
            evt.consume();
        }
}//GEN-LAST:event_jTFToleranciaKeyTyped

    private void cmbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCalcularActionPerformed
        try {
            jTFRaiz.setText("");
            objSecante = new Secante(Double.parseDouble(jTFa.getText()), Double.parseDouble(jTFb.getText()), Double.parseDouble(jTFTolerancia.getText()), Integer.parseInt(jTFn.getText()));
            objSecante.setModelo(modeloTabla);
            jTFRaiz.setText(String.format("%.6f", objSecante.calcularRaiz())); //trabajamos con 6 decimales después del punto
            lblErrores.setText("");
        } catch (Exception e) {
            lblErrores.setText(e.toString());
        }
}//GEN-LAST:event_cmbCalcularActionPerformed

    private void jTFnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFnKeyPressed
        if ((jTFn.getText().contains(".") && evt.getKeyChar() == '.') && !Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
}//GEN-LAST:event_jTFnKeyPressed

    private void jTFnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFnKeyReleased
        validarCampos();
}//GEN-LAST:event_jTFnKeyReleased

    private void jTFnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFnKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) || jTFn.getText().length() > 15) {
            evt.consume();
        }
}//GEN-LAST:event_jTFnKeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new secForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFRaiz;
    private javax.swing.JTextField jTFTolerancia;
    private javax.swing.JTextField jTFa;
    private javax.swing.JTextField jTFb;
    private javax.swing.JTextField jTFn;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblErrores;
    // End of variables declaration//GEN-END:variables

}
