package jctable;

import javax.swing.table.DefaultTableModel;
/**
*  @web http://jc-mouse.blogspot.com/
 * @author Mouse
 */
public class interfaz extends javax.swing.JFrame {
    
    Object[][] dtDatos = new Object[18][3];
    String[] columNames = {"Columna 1","Columna 2","Columna 3"};
    
    
    /** Creates new form interfaz */
    public interfaz() {
        initComponents();
        this.setTitle("jTable con Formato - [by Mouse]");
        /* se llena la tabla con algunos datos */
        dtDatos[0][0]="Hola";dtDatos[0][1]="Mundo";dtDatos[0][2]="Cruel";
        dtDatos[1][0]="Num. Real";dtDatos[1][1]="20,5";dtDatos[1][2]="73.7";        
        dtDatos[2][0]="Num. Enteros";dtDatos[2][1]="0";dtDatos[2][2]="67";
        dtDatos[3][0]="--x--";dtDatos[3][1]="--x--";dtDatos[3][2]="--x--";
        dtDatos[4][0]="";dtDatos[4][1]="jc Mouse";dtDatos[4][2]="";
        dtDatos[5][0]="";dtDatos[5][1]="de";dtDatos[5][2]="";
        dtDatos[6][0]="";dtDatos[6][1]="Bolivia";dtDatos[6][2]="";
        dtDatos[7][0]="";dtDatos[7][1]="4ever";dtDatos[7][2]="";
        //se asigna el TableModel
        DefaultTableModel TableModel = new DefaultTableModel(dtDatos,columNames);                                        
        jTable1.setModel(TableModel);
        //se asigna el formato a la tabla
        jTable1.setDefaultRenderer (Object.class, new FormatoTabla());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
