/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Clientes.java
 *
 * Created on 05-13-2011, 01:25:35 PM
 */
package ClienteChat;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.JOptionPane.*;
import java.io.*;

/**
 *
 * @author greg
 */
public class Clientes extends javax.swing.JFrame {

    String mensajecliente;
    Cliente cliente;
    VentanaAyuda va;
    JOptionPane AcercaDe;
    Vector<String> nomUsers;
    VentPrivada ventPrivada;
    


    /** Creates new form Clientes */
    public Clientes(){
        initComponents();
        //getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));
        lblNomUser.setText("Usuario <<  >>");

        txtMensage.requestFocus();//pedir el focus
        try {
            cliente = new Cliente(this);
            cliente.conexion();
        } catch (IOException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
        nomUsers = new Vector();
        ponerActivos(cliente.pedirUsuarios());
        ventPrivada = new VentPrivada(cliente);

    }

    
    public void setNombreUser(String user) {
        lblNomUser.setText("Usuario " + user);
    }

    public void mostrarMsg(String msg) {
        this.panMostrar.append(msg + "\n");
    }

    public void ponerActivos(Vector datos) {
        nomUsers = datos;
        ponerDatosList(this.lstActivos, nomUsers);
    }

    public void agregarUser(String user) {
        nomUsers.add(user);
        ponerDatosList(this.lstActivos, nomUsers);
    }

    public void retirraUser(String user) {
        nomUsers.remove(user);
        ponerDatosList(this.lstActivos, nomUsers);
    }

    private void ponerDatosList(JList list, final Vector datos) {
        list.setModel(new AbstractListModel() {

            @Override
            public int getSize() {
                return datos.size();
            }

            @Override
            public Object getElementAt(int i) {
                return datos.get(i);
            }
        });
    }

//    public void actionPerformed(ActionEvent evt) {
//
//        String comand = (String) evt.getActionCommand();
//        if (comand.compareTo("help") == 0) {
//            va = new VentanaAyuda();
//            va.setVisible(true);
//        }
//        if (comand.compareTo("Acerca") == 0) {
//            JOptionPane.showMessageDialog(this, "José Valdez/Javier Vargas", "Desarrollado por", JOptionPane.INFORMATION_MESSAGE);
//        }
//        if (evt.getSource() == this.butEnviar || evt.getSource() == this.txtMensage) {
//            String mensaje = txtMensage.getText();
//            cliente.flujo(mensaje);
//            txtMensage.setText("");
//        } else if (evt.getSource() == this.butPrivado) {
//            int pos = this.lstActivos.getSelectedIndex();
//            if (pos >= 0) {
//                ventPrivada.setAmigo(nomUsers.get(pos));
//                ventPrivada.setVisible(true);
//            }
//        }
//    }
    public void mensageAmigo(String amigo, String msg) {
        ventPrivada.setAmigo(amigo);
        ventPrivada.mostrarMsg(msg);
        ventPrivada.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panMostrar = new javax.swing.JTextArea();
        txtMensage = new javax.swing.JTextField();
        butEnviar = new javax.swing.JButton();
        lblNomUser = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstActivos = new javax.swing.JList();
        butPrivado = new javax.swing.JButton();
        jlMensajes = new javax.swing.JLabel();
        jpVideo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        JMArchivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        JMAyuda = new javax.swing.JMenu();
        help = new javax.swing.JMenuItem();
        JMAcerca = new javax.swing.JMenu();
        acercaD = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panMostrar.setColumns(20);
        panMostrar.setRows(5);
        jScrollPane1.setViewportView(panMostrar);

        txtMensage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMensageKeyReleased(evt);
            }
        });

        butEnviar.setText("Enviar");
        butEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEnviarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lstActivos);

        butPrivado.setText("Privados");
        butPrivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPrivadoActionPerformed(evt);
            }
        });

        jlMensajes.setText("      Ingrese Mensaje a Enviar:");

        jpVideo.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 204, 255)));
        jpVideo.setPreferredSize(new java.awt.Dimension(184, 144));

        javax.swing.GroupLayout jpVideoLayout = new javax.swing.GroupLayout(jpVideo);
        jpVideo.setLayout(jpVideoLayout);
        jpVideoLayout.setHorizontalGroup(
            jpVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jpVideoLayout.setVerticalGroup(
            jpVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JMArchivo.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Cargar Imagen");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        JMArchivo.add(jMenuItem1);

        barraMenu.add(JMArchivo);

        JMAyuda.setText("Ayuda");

        help.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        help.setText("help");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        JMAyuda.add(help);

        barraMenu.add(JMAyuda);

        JMAcerca.setText("Acerca de.");

        acercaD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        acercaD.setText("Creditos");
        acercaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaDActionPerformed(evt);
            }
        });
        JMAcerca.add(acercaD);

        barraMenu.add(JMAcerca);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(butPrivado, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMensage, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butEnviar, 0, 0, Short.MAX_VALUE))
                            .addComponent(jlMensajes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                        .addComponent(lblNomUser, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomUser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jlMensajes)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMensage, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(butEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jpVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butPrivado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEnviarActionPerformed
        String mensaje = txtMensage.getText();
        cliente.flujo(mensaje);
        txtMensage.setText("");
    }//GEN-LAST:event_butEnviarActionPerformed

    private void butPrivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPrivadoActionPerformed
        int pos = this.lstActivos.getSelectedIndex();
        if (pos >= 0) {
            ventPrivada.setAmigo(nomUsers.get(pos));
            ventPrivada.setVisible(true);
        }
    }//GEN-LAST:event_butPrivadoActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        va = new VentanaAyuda();
        va.setVisible(true);
    }//GEN-LAST:event_helpActionPerformed

    private void acercaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaDActionPerformed
        JOptionPane.showMessageDialog(this, "Rogel Grijalva/Gerson Edgardo", "Desarrollado por", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_acercaDActionPerformed

    private void txtMensageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMensageKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String mensaje = txtMensage.getText();
            cliente.flujo(mensaje);
            this.txtMensage.setText("");
            //System.out.println("Presionó Enter");
        }
    }//GEN-LAST:event_txtMensageKeyReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jmfVideo b = new jmfVideo();
        jpVideo.add(b.Componente());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jmfVideo b = new jmfVideo();
        jpVideo.add(b.Componente());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
              
                    Cliente.IP_SERVER = JOptionPane.showInputDialog("Introducir IP_SERVER :", "localhost");
                    new Clientes().setVisible(true);
                

//            }
//        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMAcerca;
    private javax.swing.JMenu JMArchivo;
    private javax.swing.JMenu JMAyuda;
    private javax.swing.JMenuItem acercaD;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton butEnviar;
    private javax.swing.JButton butPrivado;
    private javax.swing.JMenuItem help;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlMensajes;
    private javax.swing.JPanel jpVideo;
    private javax.swing.JLabel lblNomUser;
    private javax.swing.JList lstActivos;
    private javax.swing.JTextArea panMostrar;
    private javax.swing.JTextField txtMensage;
    // End of variables declaration//GEN-END:variables
}
