package practica;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fam Olmedo
 */
public class JFrame1 extends javax.swing.JFrame {
    private String nombr = " ";
    private DefaultTableModel modelo;
  private static FileNameExtensionFilter filter = new FileNameExtensionFilter("doc","doc & txt","txt");
    /** Creates new form JFrame1 */
    public JFrame1() {
        initComponents();
this.crearTabla();
Sexo = new ButtonGroup();
Sexo.add(jRadioButtonMasc);
Sexo.add(jRadioButtonFem);
    }

    public void crearTabla(){
         modelo = new DefaultTableModel();
          modelo.addColumn("Nombre:");
          modelo.addColumn("Apellido:");
          modelo.addColumn("Edad:");
          modelo.addColumn("Pais");
          modelo.addColumn("Sexo:");
          this.jTable.setModel(modelo);
    }

public void Nuevo() throws IOException{
    jTextFieldNom.setText("Nombre ");
    jTextFieldApe.setText("Apellido ");
    jRadioButtonFem.setSelected(false);
    jRadioButtonMasc.setSelected(false);
    jComboBoxPais.setSelectedIndex(0);
    this.jSpinnerEdad.setValue(0);
}

public void guardar() throws IOException{
    try {
        String tabla = null;
        JFileChooser guardar = new JFileChooser();
        guardar.setFileFilter(filter);
        guardar.setCurrentDirectory(null);
        guardar.showSaveDialog(this);
        File Guardar = guardar.getSelectedFile();
        if (Guardar != null){
            nombr = guardar.getSelectedFile().getName();
            FileWriter guard = new FileWriter(Guardar);
            guard.write(jLabelNom.getText());
            guard.write(" " + jLabelApe.getText());
            guard.write(" " + jLabelEdad.getText());
            guard.write(" " + jLabelPais.getText());
            guard.write(" " + jLabelSexo.getText());
     for(int numFila=0; numFila<modelo.getRowCount();numFila++){
         for (int numColum=0; numColum<modelo.getColumnCount(); numColum++){
             tabla = modelo.getValueAt(numFila,numColum).toString();
             guard.flush();
             guard.write(tabla + " ");
         }
         guard.write(" \n ");
         guard.write(" \n ");
     }
            guard.close();
        }
    } catch (IOException ioe) {
    System.out.println(ioe);
    }
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sexo = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelNom = new javax.swing.JLabel();
        jLabelApe = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldApe = new javax.swing.JTextField();
        jLabelEdad = new javax.swing.JLabel();
        jSpinnerEdad = new javax.swing.JSpinner();
        jLabelSexo = new javax.swing.JLabel();
        jRadioButtonMasc = new javax.swing.JRadioButton();
        jRadioButtonFem = new javax.swing.JRadioButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonNuevos = new javax.swing.JButton();
        jLabelPais = new javax.swing.JLabel();
        jComboBoxPais = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButtonModificarDatos = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(java.awt.Color.blue);

        jPanel1.setBackground(java.awt.Color.blue);

        jLabelNom.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNom.setForeground(java.awt.Color.white);
        jLabelNom.setText("Nombre");

        jLabelApe.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApe.setText("Apellido");

        jTextFieldNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomKeyTyped(evt);
            }
        });

        jTextFieldApe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApeKeyTyped(evt);
            }
        });

        jLabelEdad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdad.setText("Edad");

        jSpinnerEdad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        jLabelSexo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSexo.setText("Sexo");

        jRadioButtonMasc.setText("Masculino");

        jRadioButtonFem.setText("Femenino");

        jButtonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica/imagen/guardar1.png"))); // NOI18N
        jButtonAgregar.setText("Agregar Tabla");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButtonNuevos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica/imagen/nuevo.png"))); // NOI18N
        jButtonNuevos.setText("Nuevos Datos");
        jButtonNuevos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevosActionPerformed(evt);
            }
        });

        jLabelPais.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPais.setText("Pais");

        jComboBoxPais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "El Salvador", "España", "Argentina", "Brasil", "EEUU", "Costa Rica", "Panama", "Guatemala", "Peru", "Chile", "Nigeria", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelEdad)
                            .addComponent(jLabelApe)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelSexo)
                                .addComponent(jLabelPais)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinnerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPais, 0, 224, Short.MAX_VALUE)
                    .addComponent(jTextFieldApe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonMasc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonNuevos, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonFem))))
                .addGap(471, 471, 471))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNom))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelApe))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEdad))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPais))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMasc)
                    .addComponent(jRadioButtonFem)
                    .addComponent(jLabelSexo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevos)
                    .addComponent(jButtonAgregar))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Datos", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable);

        jButtonModificarDatos.setText("Modificar Datos");

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButtonModificarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(393, 393, 393))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModificarDatos)
                    .addComponent(jButtonGuardar))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tabla", jPanel2);

        jMenu1.setText("Guardar");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:
        String nombre = jTextFieldNom.getText();
        String apellido = jTextFieldApe.getText();
        String sexo= "";
        if (jRadioButtonMasc.isSelected()==true){
            sexo = jRadioButtonMasc.getText();
        }
        if(jRadioButtonFem.isSelected()==true){
            sexo = jRadioButtonFem.getText();
        }
        String pais = (String) jComboBoxPais.getSelectedItem();
        Integer Edad = (Integer) this.jSpinnerEdad.getValue();
        Object [] fila = {nombre,apellido,Edad,pais,sexo};
        modelo.addRow(fila);
        this.jTable.setModel(modelo);
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonNuevosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevosActionPerformed
        // TODO add your handling code here:
        try {
            Nuevo();
        } catch (IOException e) {
        Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE,null,e);
        }
    }//GEN-LAST:event_jButtonNuevosActionPerformed

    private void jTextFieldNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomKeyTyped
        // TODO add your handling code here:
        if (!Character.isLetter(evt.getKeyChar())&&!Character.isSpaceChar(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNomKeyTyped

    private void jTextFieldApeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApeKeyTyped
        // TODO add your handling code here:
        if (!Character.isLetter(evt.getKeyChar())&&!Character.isSpaceChar(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldApeKeyTyped

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        try {
            guardar();
        } catch (Exception e) {
           Logger.getLogger(JFrame1.class.getName()).log(Level.SEVERE,null,e);
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed



    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonModificarDatos;
    private javax.swing.JButton jButtonNuevos;
    private javax.swing.JComboBox jComboBoxPais;
    private javax.swing.JLabel jLabelApe;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPais;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonFem;
    private javax.swing.JRadioButton jRadioButtonMasc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerEdad;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldApe;
    private javax.swing.JTextField jTextFieldNom;
    // End of variables declaration//GEN-END:variables

}
