package jcmaccesscurso;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 * @web http://jc-mouse.blogspot.com/
 * @author Mouse
 */
public class matricula extends javax.swing.JInternalFrame {
    SQL sql = new SQL();
    jcm_mensajes msg = new jcm_mensajes();
    
    Object[] dtDep; 
    Object[] dtAs; 
    String asignatura="";
    String gestion="";
    
    
    /** Creates new form matricula */
    public matricula() {
        initComponents();
        this.setTitle("Matriculacion de Alumnos - by Mouse");
        //dije matriculacion ;)
        Actualizar_Combos();
        //Actualizar_Tabla(asignatura, gestion);
        //se asigna el formato a la tabla
        tabla.setDefaultRenderer (Object.class, new FormatoTabla());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboAsignatura = new javax.swing.JComboBox();
        cboAlumno = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cboGestion = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        cmdCerrar = new javax.swing.JButton();
        cmdMatricular = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/screen3.jpg"))); // NOI18N
        jcMousePanel1.setPreferredSize(new java.awt.Dimension(560, 470));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo Asignatura:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Carnet Universitario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel1.add(jLabel2, gridBagConstraints);

        cboAsignatura.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboAsignatura.setPreferredSize(new java.awt.Dimension(180, 20));
        cboAsignatura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboAsignaturaMouseClicked(evt);
            }
        });
        cboAsignatura.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboAsignaturaItemStateChanged(evt);
            }
        });
        cboAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAsignaturaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel1.add(cboAsignatura, gridBagConstraints);

        cboAlumno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboAlumno.setPreferredSize(new java.awt.Dimension(180, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel1.add(cboAlumno, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gestion:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel1.add(jLabel3, gridBagConstraints);

        cboGestion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01/10", "02/10", "01/11" }));
        cboGestion.setPreferredSize(new java.awt.Dimension(180, 20));
        cboGestion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboGestionItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel1.add(cboGestion, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addContainerGap())
        );

        cmdCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/door.png"))); // NOI18N
        cmdCerrar.setText("Cerrar");
        cmdCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCerrarActionPerformed(evt);
            }
        });

        cmdMatricular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mat.png"))); // NOI18N
        cmdMatricular.setText("Matricular");
        cmdMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMatricularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdMatricular, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jcMousePanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCerrarActionPerformed
        sql.Cerrar_Access();
        dispose();
    }//GEN-LAST:event_cmdCerrarActionPerformed

    private void cmdMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMatricularActionPerformed
        //los datos y el orden de inserccion
        String[] datos = { cboAlumno.getSelectedItem().toString(),cboAsignatura.getSelectedItem().toString(),cboGestion.getSelectedItem().toString() };      
        if(sql.Nueva_Matricula(datos)){
            JOptionPane.showMessageDialog(this,msg.getNuevoRegistro());
        }else{
            JOptionPane.showMessageDialog(this,msg.getError());
        }
        change();
    }//GEN-LAST:event_cmdMatricularActionPerformed

    private void cboAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAsignaturaActionPerformed

    }//GEN-LAST:event_cboAsignaturaActionPerformed

    private void cboAsignaturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboAsignaturaMouseClicked
        this.asignatura = cboAsignatura.getSelectedItem().toString();
        this.gestion = cboGestion.getSelectedItem().toString();
        Actualizar_Tabla(asignatura,gestion);
    }//GEN-LAST:event_cboAsignaturaMouseClicked

    private void cboAsignaturaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboAsignaturaItemStateChanged
        change(); 
    }//GEN-LAST:event_cboAsignaturaItemStateChanged

    private void cboGestionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboGestionItemStateChanged
        change();
    }//GEN-LAST:event_cboGestionItemStateChanged

 private void change(){
        if(cboAsignatura.getSelectedItem()!=null && cboGestion.getSelectedItem()!=null){
            this.asignatura = cboAsignatura.getSelectedItem().toString();
            this.gestion = cboGestion.getSelectedItem().toString();            
            Actualizar_Tabla(asignatura,gestion);
        }      
 }
         
 private void Actualizar_Combos(){  
    //rellena el objeto combobox con los valores de la tabla departamento
    dtDep =   sql.getDatosAlumno2();
    cboAlumno.removeAllItems();
    for(int i=0; i<=dtDep.length-1;i++){
        cboAlumno.addItem(dtDep[i].toString());        
    }   
    
    dtAs =   sql.getDatosAsignatura2();
    cboAsignatura.removeAllItems();
    for(int i=0; i<=dtAs.length-1;i++){
        cboAsignatura.addItem(dtAs[i].toString());        
    }       
}
    
 private void Actualizar_Tabla(String a, String g){                    
        // se colocan los datos en la tabla
        DefaultTableModel datos = sql.getDatosMatricula(a, g);
        tabla.setModel(datos);       
}
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboAlumno;
    private javax.swing.JComboBox cboAsignatura;
    private javax.swing.JComboBox cboGestion;
    private javax.swing.JButton cmdCerrar;
    private javax.swing.JButton cmdMatricular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
    
}
