/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdministrarVehiculos.java
 *
 * Created on 11-jun-2012, 23:56:29
 */
package vistas;

import Instancia.InstanceOf;
import accesoDatos.Operaciones;
import accesoDatos.OperacionesUsuarios;
import clases.Vehiculo;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chavez Vigil
 */
public class AdministrarVehiculos extends javax.swing.JFrame {

    public int filaAnterior = 0;
    Operaciones op = new Operaciones();
    OperacionesUsuarios opU = new OperacionesUsuarios();
    RutaRecDomiciliar recoleccionDomiciliar = new RutaRecDomiciliar();
    String usu;

    /** Creates new form AdministrarVehiculos */
    public AdministrarVehiculos() {
        initComponents();
        op.listarVehiculo(jtVehiculos);
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/iconBLH.png"));
        return retValue;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jlIndiceOculto1 = new javax.swing.JLabel();
        jlIndiceOculto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtVehiculos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jbEliminar = new javax.swing.JButton();
        jbNuevoVehiculo = new javax.swing.JButton();
        jbModificar2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbAgregar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrar Vehículos - Banco de Leche Humana");
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(701, 505));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(142, 180, 227));

        jtVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"N245022", "Pick - Up"},
                {"N434569", "Camioneta"}
            },
            new String [] {
                "Placa Vehículo", "Tipo Vehículo"
            }
        ));
        jtVehiculos.setRowHeight(25);
        jtVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtVehiculosMouseClicked(evt);
            }
        });
        jtVehiculos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtVehiculosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtVehiculosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtVehiculos);

        jPanel2.setBackground(new java.awt.Color(142, 180, 227));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 102))); // NOI18N
        net.java.dev.koalalayout.KoalaLayout koalaLayout1 = new net.java.dev.koalalayout.KoalaLayout();
        koalaLayout1.setGridheight(10);
        koalaLayout1.setGridwidth(10);
        jPanel2.setLayout(koalaLayout1);

        jbEliminar.setFont(new java.awt.Font("Tahoma", 1, 18));
        jbEliminar.setText("Eliminar Vehículo");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        jPanel2.add(jbEliminar, gridBagConstraints);

        jbNuevoVehiculo.setFont(new java.awt.Font("Tahoma", 1, 18));
        jbNuevoVehiculo.setText("Nuevo Vehículo");
        jbNuevoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoVehiculoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        jPanel2.add(jbNuevoVehiculo, gridBagConstraints);

        jbModificar2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jbModificar2.setText("Guardar");
        jbModificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificar2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        jPanel2.add(jbModificar2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(142, 180, 227));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jbAgregar.setFont(new java.awt.Font("Tahoma", 1, 18));
        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jbAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/motoIcon.png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jlIndiceOculto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jlIndiceOculto1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(82, 82, 82))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlIndiceOculto1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlIndiceOculto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-717)/2, (screenSize.height-543)/2, 717, 543);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        recoleccionDomiciliar.vehiculo = "";
//        new RutaRecDomiciliar().setVisible(true);
//        this.setVisible(false);
        comoSalir2();
    }//GEN-LAST:event_jButton1ActionPerformed

private void jbNuevoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoVehiculoActionPerformed
    // TODO add your handling code here:
    try {
        DefaultTableModel model = (DefaultTableModel) jtVehiculos.getModel();
        Object fila[] = {"", "",};
        model.addRow(fila);
//        filaAnterior = jtVehiculos.getSelectedRow();
        this.jbNuevoVehiculo.setEnabled(false);
    } catch (Exception e) {
    }
}//GEN-LAST:event_jbNuevoVehiculoActionPerformed

private void jbModificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificar2ActionPerformed
    // TODO add your handling code here:

    try {
        if (jtVehiculos.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(rootPane, "¡Seleccione vehiculo para almacenar!");
        } else if (jtVehiculos.getValueAt(jtVehiculos.getSelectedRow(), 0).equals("") || jtVehiculos.getValueAt(jtVehiculos.getSelectedRow(), 1).equals("")) {
            JOptionPane.showMessageDialog(rootPane, "¡Por favor, complete datos del Vehículo!");
        } else {
            Vehiculo vehiculo = new Vehiculo(jtVehiculos.getValueAt(jtVehiculos.getSelectedRow(), 0).toString(), jtVehiculos.getValueAt(jtVehiculos.getSelectedRow(), 1).toString());
            op.almacenarVehiculo(vehiculo);
            this.jbNuevoVehiculo.setEnabled(true);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Error al almacenar: " + e.getMessage());
    }
}//GEN-LAST:event_jbModificar2ActionPerformed

private void jtVehiculosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtVehiculosKeyPressed
    filaAnterior = jtVehiculos.getSelectedRow();

}//GEN-LAST:event_jtVehiculosKeyPressed

private void jtVehiculosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtVehiculosKeyReleased
    int key = evt.getKeyChar();

    System.out.println("FILA: " + filaAnterior);
    if (key == KeyEvent.VK_TAB && !jtVehiculos.getValueAt(filaAnterior, 0).equals("") && !jtVehiculos.getValueAt(filaAnterior, 1).equals("")) {
        Vehiculo vehiculo = new Vehiculo(jtVehiculos.getValueAt(filaAnterior, 0).toString(), jtVehiculos.getValueAt(filaAnterior, 1).toString());
        op.almacenarVehiculo(vehiculo);
        this.jbNuevoVehiculo.setEnabled(true);
    }}//GEN-LAST:event_jtVehiculosKeyReleased

private void jtVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtVehiculosMouseClicked
    filaAnterior = jtVehiculos.getSelectedRow();
}//GEN-LAST:event_jtVehiculosMouseClicked

private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
    try {
        if (jtVehiculos.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione Vehículo a eliminar!");
        } else {
            int msj = JOptionPane.showConfirmDialog(rootPane, "¿En verdad desea eliminar?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (msj == 0) {
                if (opU.isAdmin()) {
                    String V = jtVehiculos.getValueAt(jtVehiculos.getSelectedRow(), 0).toString();
                    usu = opU.usuarioUp();
                    opU.setEstado(usu, "El. Vehiculo " + V);
                    Vehiculo carro = new Vehiculo(jtVehiculos.getValueAt(jtVehiculos.getSelectedRow(), 0).toString(), jtVehiculos.getValueAt(jtVehiculos.getSelectedRow(), 1).toString());
                    op.eliminarVehiculo(carro);
                    DefaultTableModel model = (DefaultTableModel) jtVehiculos.getModel();
                    model.removeRow(jtVehiculos.getSelectedRow());

                } else {
                    JOptionPane.showMessageDialog(null, "Lo siento, usted no esta autorizado para realizar esta acción\nsolo un administrador puede hacerlo", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Error: " + e.getMessage());
    }

}//GEN-LAST:event_jbEliminarActionPerformed

private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
    if (jtVehiculos.getSelectedRow() == -1) {
        JOptionPane.showMessageDialog(rootPane, "¡Debe seleccionar una vehículo!");
    } else {
        try {
            comoSalir();
            RutaRecDomiciliar.jbModificar.setVisible(false);
            RutaRecDomiciliar.jbEliminar.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error: " + e.getMessage());
        }
    }
}//GEN-LAST:event_jbAgregarActionPerformed

private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    comoSalir2();
}//GEN-LAST:event_formWindowClosed

    public void comoSalir() {
        int var = Integer.parseInt(jlIndiceOculto.getText());
        switch (var) {
            case 1:
                this.hide();
                break;
            case 2:
//                new InstanceOfConsult().consulta.setVisible(true);
//                ControlPacientes.jtfMedico.setText(this.jtMedicos.getValueAt(this.jtMedicos.getSelectedRow(), 0).toString());

                RutaRecDomiciliar.vehiculo = (this.jtVehiculos.getValueAt(jtVehiculos.getSelectedRow(), 0).toString());
                new InstanceOf().rutRecDom.setVisible(true);
                RutaRecDomiciliar.jlIndiceOc.setText(jlIndiceOculto1.getText());

                //                Consult.jtfMedico.setText(this.jtMedicos.getValueAt(this.jtMedicos.getSelectedRow(), 0).toString());
//                RutaRecDomiciliar.jlIndiceOc.setText(jlIndiceOculto1.getText());
                this.hide();
                break;
        }
    }

    public void comoSalir2() {
        int var = Integer.parseInt(jlIndiceOculto.getText());
        switch (var) {
            case 1:
                this.hide();
                break;
            case 2:
                new InstanceOf().rutRecDom.setVisible(true);
//                ControlPacientes.jtfMedico.setText(this.jtMedicos.getValueAt(this.jtMedicos.getSelectedRow(), 0).toString());
//                Consult.jtfMedico.setText(this.jtMedicos.getValueAt(this.jtMedicos.getSelectedRow(), 0).toString());
//                RutaRecDomiciliar.jlIndiceOc.setText(jlIndiceOculto1.getText());
                RutaRecDomiciliar.jlIndiceOc.setText(jlIndiceOculto1.getText());
                this.hide();
                break;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrarVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrarVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrarVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrarVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AdministrarVehiculos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbModificar2;
    private javax.swing.JButton jbNuevoVehiculo;
    public static javax.swing.JLabel jlIndiceOculto;
    public static javax.swing.JLabel jlIndiceOculto1;
    private javax.swing.JTable jtVehiculos;
    // End of variables declaration//GEN-END:variables
}
