/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ControlPaciente.java
 *
 * Created on 10-sep-2012, 17:48:55
 */
package vistas;

import Instancia.InstanceOf;
import Instancia.InstanceOfConsult;
import Operaciones.OperacionesExcel;
import accesoDatos.OperacionesDonantNinos;
import Operaciones.OperacionesReportes;
import Operaciones.OperacionesInformes;
import accesoDatos.OperacionesConsulta;
import accesoDatos.OperacionesUsuarios;
import clases.Calculos;
import clases.Consulta;
import clases.Paciente;
import clases.PropiedadesPaciente;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.write.WriteException;

/**
 *
 * @author Chavez Vigil
 */
public class ControlPaciente extends javax.swing.JFrame {

    /** Creates new form ControlPaciente */
    OperacionesReportes opr = new OperacionesReportes();
    OperacionesConsulta op = new OperacionesConsulta();
    OperacionesDonantNinos opDN = new OperacionesDonantNinos();
    OperacionesInformes opi = new OperacionesInformes();
    OperacionesExcel opx = new OperacionesExcel();
    Calculos calculos = new Calculos();
    OperacionesUsuarios opU = new OperacionesUsuarios();
    String usu = "";
    public String nombre = "";
    public String apellido = "";
    public String sexo = "";
    public String carnet = "";
    public String semGes = "";
    public Date fechaNa = null;
    public String patologias = "";
    public String municipio = "";
    public String departamento = "";
    public String edadMaterna = "";
    public String gravidez = "";
    public String parto = "";
    public String tipo = "";
    static public String Encargado = "";
    public String Notas = "";
    Paciente pte;
    PropiedadesPaciente propiedades;
    BuscarNino buscar = new BuscarNino();
    String value = "";

    public ControlPaciente() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        fechaNa = jcfechaNac.getDate();
        semGes = jsSemGestacion.getValue().toString();
        opDN.listarNinos(jtPacientes);
        calculos.Municipios(0, jcbMunicipio);
        this.patologias = jcbPatologias.getSelectedItem().toString();
        this.parto = jcbParto.getSelectedItem().toString();
        this.tipo = jcbTipoNiño.getSelectedItem().toString();
        this.edadMaterna = jsEdadMaterna.getValue().toString();
        this.departamento = jcbDepartamento.getSelectedItem().toString();
        this.municipio = jcbMunicipio.getSelectedItem().toString();
        jtfEncargado.setEditable(false);
        jtConsultas.setModel(buscar.model);
        
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/iconBLH.png"));
        return retValue;
    }

    public void limpiarHabilitarValores() {
        Encargado = "";
        jcfechaNac.setDate(new Date());
        jlEdad.setText("");
        jlNumeroConsultas.setText("");
        jlNombreEncargado.setText("");
        jtfNombres.setText("");
        jtfApellidos.setText("");
        jtfTarjeta.setText("");
        jtfEncargado.setText("");
        jtfNotas.setText("");
        jrbFemenino.setSelected(false);
        jrbMasculino.setSelected(false);
        jtfPalabraBuscar.setText("");
        jsGravidez.setValue(1);
        jtfPatologias.setText("");
        jcbParto.setSelectedIndex(0);
        jcbTipoNiño.setSelectedIndex(0);
        jcbPatologias.setSelectedIndex(0);
        jcbDepartamento.setSelectedIndex(0);
        jcbMunicipio.setSelectedIndex(0);
        jsEdadMaterna.setValue(15);
        jsSemGestacion.setValue(36);
    }

    public void calcularEdad(Date fecha) {
        try {
            java.util.Date hoy = new Date(); 
            int anio = ((hoy.getYear() +1900) - (fecha.getYear()+1900));//Fecha de hoy 
            int meses = ((hoy.getMonth() +1) - (fecha.getMonth()+1));
            int d = (hoy.getDate() - fecha.getDate());
            jlEdad.setText(anio + " Años "+meses +" Meses " +d +" Dias");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bgSexoNino = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jbAbrirConsulta = new javax.swing.JButton();
        jbNuevaConsulta = new javax.swing.JButton();
        jbEliminarConsulta = new javax.swing.JButton();
        jlNumeroConsultas = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jcbSeleccionarBusquedaConsulta = new javax.swing.JComboBox();
        jtfPalabraBuscar = new javax.swing.JTextField();
        jbBuscarConsulta = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jbExcel = new javax.swing.JButton();
        jbReporte = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jbNuevoNino = new javax.swing.JButton();
        jbAbrirNino = new javax.swing.JButton();
        jbEliminarNino = new javax.swing.JButton();
        jbBuscarNino = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbCancelar = new javax.swing.JButton();
        jbAlmacenar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtConsultas = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jrbMasculino = new javax.swing.JRadioButton();
        jrbFemenino = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtfNombres = new javax.swing.JTextField();
        jtfApellidos = new javax.swing.JTextField();
        jtfTarjeta = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jsSemGestacion = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jcfechaNac = new org.freixas.jcalendar.JCalendarCombo();
        jlEdad = new javax.swing.JLabel();
        jcbDepartamento = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcbMunicipio = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jbOtrosDatos = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtfNotas = new javax.swing.JEditorPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jtfEncargado = new javax.swing.JTextField();
        jbAgregarEncargado = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jcbParto = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jsEdadMaterna = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jcbPatologias = new javax.swing.JComboBox();
        jtfPatologias = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jcbTipoNiño = new javax.swing.JComboBox();
        jsGravidez = new javax.swing.JSpinner();
        jlNombreEncargado = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtPacientes = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pacientes - Banco de Leche Humana");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        net.java.dev.koalalayout.KoalaLayout koalaLayout9 = new net.java.dev.koalalayout.KoalaLayout();
        koalaLayout9.setGridheight(22);
        koalaLayout9.setGridwidth(26);
        jPanel1.setLayout(koalaLayout9);

        jPanel8.setBackground(new java.awt.Color(85, 142, 213));
        net.java.dev.koalalayout.KoalaLayout koalaLayout1 = new net.java.dev.koalalayout.KoalaLayout();
        koalaLayout1.setGridheight(5);
        koalaLayout1.setGridwidth(42);
        jPanel8.setLayout(koalaLayout1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel3.setText("Consultas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        jPanel8.add(jLabel3, gridBagConstraints);

        jbAbrirConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/folder.png"))); // NOI18N
        jbAbrirConsulta.setToolTipText("Abrir Consulta Seleccionada");
        jbAbrirConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAbrirConsultaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        jPanel8.add(jbAbrirConsulta, gridBagConstraints);

        jbNuevaConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        jbNuevaConsulta.setToolTipText("Añadir Consulta");
        jbNuevaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevaConsultaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        jPanel8.add(jbNuevaConsulta, gridBagConstraints);

        jbEliminarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        jbEliminarConsulta.setToolTipText("Eliminar Consulta");
        jbEliminarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarConsultaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        jPanel8.add(jbEliminarConsulta, gridBagConstraints);

        jlNumeroConsultas.setFont(new java.awt.Font("Tahoma", 2, 14));
        jlNumeroConsultas.setText("cant.: n");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        jPanel8.add(jlNumeroConsultas, gridBagConstraints);

        jLabel18.setBackground(new java.awt.Color(255, 204, 204));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Buscar por:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 3;
        jPanel8.add(jLabel18, gridBagConstraints);

        jcbSeleccionarBusquedaConsulta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todas", "Fecha Consulta", "JVPM (Médico)" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 19;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 3;
        jPanel8.add(jcbSeleccionarBusquedaConsulta, gridBagConstraints);

        jtfPalabraBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfPalabraBuscarFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 28;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 3;
        jPanel8.add(jtfPalabraBuscar, gridBagConstraints);

        jbBuscarConsulta.setText("Buscar");
        jbBuscarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarConsultaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 36;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        jPanel8.add(jbBuscarConsulta, gridBagConstraints);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 5;
        jPanel8.add(jSeparator1, gridBagConstraints);

        jbExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/page_excel.png"))); // NOI18N
        jbExcel.setToolTipText("Exportar a Excel");
        jbExcel.setEnabled(false);
        jbExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        jPanel8.add(jbExcel, gridBagConstraints);

        jbReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Print.png"))); // NOI18N
        jbReporte.setToolTipText("Imprimir Consultas");
        jbReporte.setEnabled(false);
        jbReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReporteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        jPanel8.add(jbReporte, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.gridheight = 2;
        jPanel1.add(jPanel8, gridBagConstraints);

        jPanel7.setBackground(new java.awt.Color(85, 142, 213));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        net.java.dev.koalalayout.KoalaLayout koalaLayout2 = new net.java.dev.koalalayout.KoalaLayout();
        koalaLayout2.setGridheight(2);
        koalaLayout2.setGridwidth(20);
        jPanel7.setLayout(koalaLayout2);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        jPanel7.add(jSeparator2, gridBagConstraints);

        jbNuevoNino.setBackground(new java.awt.Color(255, 255, 255));
        jbNuevoNino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        jbNuevoNino.setToolTipText("Añadir nuevo niño");
        jbNuevoNino.setBorder(null);
        jbNuevoNino.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbNuevoNino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoNinoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        jPanel7.add(jbNuevoNino, gridBagConstraints);

        jbAbrirNino.setBackground(new java.awt.Color(255, 255, 255));
        jbAbrirNino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/folder.png"))); // NOI18N
        jbAbrirNino.setToolTipText("Abrir niño seleccionado");
        jbAbrirNino.setBorder(null);
        jbAbrirNino.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbAbrirNino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAbrirNinoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        jPanel7.add(jbAbrirNino, gridBagConstraints);

        jbEliminarNino.setBackground(new java.awt.Color(255, 255, 255));
        jbEliminarNino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        jbEliminarNino.setToolTipText("Borrar niño seleccionado");
        jbEliminarNino.setBorder(null);
        jbEliminarNino.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbEliminarNino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarNinoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        jPanel7.add(jbEliminarNino, gridBagConstraints);

        jbBuscarNino.setBackground(new java.awt.Color(255, 255, 255));
        jbBuscarNino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/magnifier.png"))); // NOI18N
        jbBuscarNino.setToolTipText("Buscar niño");
        jbBuscarNino.setBorder(null);
        jbBuscarNino.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbBuscarNino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarNinoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        jPanel7.add(jbBuscarNino, gridBagConstraints);

        jLabel12.setBackground(new java.awt.Color(255, 204, 204));
        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 12));
        jLabel12.setText("  Niños");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 20;
        jPanel7.add(jLabel12, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        jPanel1.add(jPanel7, gridBagConstraints);

        jPanel6.setBackground(new java.awt.Color(85, 142, 213));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        net.java.dev.koalalayout.KoalaLayout koalaLayout3 = new net.java.dev.koalalayout.KoalaLayout();
        koalaLayout3.setGridheight(2);
        koalaLayout3.setGridwidth(21);
        jPanel6.setLayout(koalaLayout3);

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel1.setText("Niño:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        jPanel6.add(jLabel1, gridBagConstraints);

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel_1.png"))); // NOI18N
        jbCancelar.setToolTipText("Limpiar Campos");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        jPanel6.add(jbCancelar, gridBagConstraints);

        jbAlmacenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disk.png"))); // NOI18N
        jbAlmacenar.setToolTipText("Guardar Datos Paciente");
        jbAlmacenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlmacenarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        jPanel6.add(jbAlmacenar, gridBagConstraints);

        jbModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Modify.png"))); // NOI18N
        jbModificar.setEnabled(false);
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        jPanel6.add(jbModificar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.gridheight = 2;
        jPanel1.add(jPanel6, gridBagConstraints);

        jtConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Carnet", "Medico", "Peso (lb)", "Longitud (cm)", "Per. Cefálico", "Ración ", "Cond. Salud", "Diagnóstico"
            }
        ));
        jtConsultas.setRowHeight(27);
        jScrollPane4.setViewportView(jtConsultas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.gridheight = 6;
        jPanel1.add(jScrollPane4, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        net.java.dev.koalalayout.KoalaLayout koalaLayout8 = new net.java.dev.koalalayout.KoalaLayout();
        koalaLayout8.setGridwidth(3);
        jPanel5.setLayout(koalaLayout8);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        net.java.dev.koalalayout.KoalaLayout koalaLayout4 = new net.java.dev.koalalayout.KoalaLayout();
        koalaLayout4.setGridheight(14);
        koalaLayout4.setGridwidth(20);
        jPanel2.setLayout(koalaLayout4);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Apellidos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        jPanel2.add(jLabel7, gridBagConstraints);

        jrbMasculino.setBackground(new java.awt.Color(255, 255, 255));
        bgSexoNino.add(jrbMasculino);
        jrbMasculino.setText("Masculino");
        jrbMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMasculinoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        jPanel2.add(jrbMasculino, gridBagConstraints);

        jrbFemenino.setBackground(new java.awt.Color(255, 255, 255));
        bgSexoNino.add(jrbFemenino);
        jrbFemenino.setText("Femenino");
        jrbFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFemeninoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        jPanel2.add(jrbFemenino, gridBagConstraints);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Sexo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        jPanel2.add(jLabel8, gridBagConstraints);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Nombres:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        jPanel2.add(jLabel15, gridBagConstraints);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("# Exped:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        jPanel2.add(jLabel16, gridBagConstraints);

        jtfNombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNombresFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.gridheight = 2;
        jPanel2.add(jtfNombres, gridBagConstraints);

        jtfApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfApellidosFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.gridheight = 2;
        jPanel2.add(jtfApellidos, gridBagConstraints);

        jtfTarjeta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfTarjetaFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.gridheight = 2;
        jPanel2.add(jtfTarjeta, gridBagConstraints);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondos/fondito2.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.gridheight = 14;
        jPanel2.add(jLabel22, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        jPanel5.add(jPanel2, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        net.java.dev.koalalayout.KoalaLayout koalaLayout5 = new net.java.dev.koalalayout.KoalaLayout();
        koalaLayout5.setGridheight(24);
        koalaLayout5.setGridwidth(20);
        jPanel3.setLayout(koalaLayout5);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Fecha de nacimiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 2;
        jPanel3.add(jLabel10, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Edad (Actual):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        jPanel3.add(jLabel9, gridBagConstraints);

        jsSemGestacion.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(36), null, null, Integer.valueOf(1)));
        jsSemGestacion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsSemGestacionStateChanged(evt);
            }
        });
        jsSemGestacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jsSemGestacionFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 3;
        jPanel3.add(jsSemGestacion, gridBagConstraints);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Semanas de Gestación:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.gridheight = 3;
        jPanel3.add(jLabel14, gridBagConstraints);

        jcfechaNac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "sábado 1 de enero de 2011" }));
        jcfechaNac.setDate(new java.util.Date(1341204951000L));
        jcfechaNac.addDateListener(new org.freixas.jcalendar.DateListener() {
            public void dateChanged(org.freixas.jcalendar.DateEvent evt) {
                jcfechaNacDateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.gridheight = 3;
        jPanel3.add(jcfechaNac, gridBagConstraints);

        jlEdad.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.gridheight = 2;
        jPanel3.add(jlEdad, gridBagConstraints);

        jcbDepartamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ahuachapan", "Cuscatlan", "Chalatenango", "Cabañas", "La Libertad", "La Unión", "La Paz", "Morazán", "Sonsonate", "Santa Ana", "San Vicente", "San Salvador", "San Miguel", "Usulután", "Fuera del país" }));
        jcbDepartamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbDepartamentoItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.gridheight = 3;
        jPanel3.add(jcbDepartamento, gridBagConstraints);

        jLabel4.setText("Departamento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 3;
        jPanel3.add(jLabel4, gridBagConstraints);

        jLabel6.setText("Municipio: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 3;
        jPanel3.add(jLabel6, gridBagConstraints);

        jcbMunicipio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbMunicipioItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.gridheight = 3;
        jPanel3.add(jcbMunicipio, gridBagConstraints);

        jLabel20.setText("Otros Datos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        jPanel3.add(jLabel20, gridBagConstraints);

        jbOtrosDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        jbOtrosDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOtrosDatosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        jPanel3.add(jbOtrosDatos, gridBagConstraints);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondos/fondito3.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.gridheight = 24;
        jPanel3.add(jLabel23, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        jPanel5.add(jPanel3, gridBagConstraints);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        net.java.dev.koalalayout.KoalaLayout koalaLayout7 = new net.java.dev.koalalayout.KoalaLayout();
        koalaLayout7.setGridheight(4);
        jPanel9.setLayout(koalaLayout7);

        jLabel5.setText("Notas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel9.add(jLabel5, gridBagConstraints);

        jtfNotas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNotasFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jtfNotas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        jPanel9.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel5.add(jPanel9, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        net.java.dev.koalalayout.KoalaLayout koalaLayout6 = new net.java.dev.koalalayout.KoalaLayout();
        koalaLayout6.setGridheight(11);
        koalaLayout6.setGridwidth(20);
        jPanel4.setLayout(koalaLayout6);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Encargado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        jPanel4.add(jLabel11, gridBagConstraints);

        jtfEncargado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfEncargadoFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 11;
        jPanel4.add(jtfEncargado, gridBagConstraints);

        jbAgregarEncargado.setText("Agregar");
        jbAgregarEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarEncargadoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        jPanel4.add(jbAgregarEncargado, gridBagConstraints);

        jLabel13.setText("Tipo Parto: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        jPanel4.add(jLabel13, gridBagConstraints);

        jcbParto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cesárea", "Natural (Vaginal)" }));
        jcbParto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbPartoItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 12;
        jPanel4.add(jcbParto, gridBagConstraints);

        jLabel17.setText("Edad Materna:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 7;
        jPanel4.add(jLabel17, gridBagConstraints);

        jsEdadMaterna.setModel(new javax.swing.SpinnerNumberModel(15, 10, 80, 1));
        jsEdadMaterna.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsEdadMaternaStateChanged(evt);
            }
        });
        jsEdadMaterna.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jsEdadMaternaFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        jPanel4.add(jsEdadMaterna, gridBagConstraints);

        jLabel19.setText("Patología Previa:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 7;
        jPanel4.add(jLabel19, gridBagConstraints);

        jcbPatologias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Madre Sana", "Diabetes Mellitus", "Infeccion de Vias Urinarias", "Hipertension Arterial", "Preeclampsia", "Eclampsia", "Sindrome de Hellp", "Otras Patologías" }));
        jcbPatologias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbPatologiasItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 12;
        jPanel4.add(jcbPatologias, gridBagConstraints);

        jtfPatologias.setEnabled(false);
        jtfPatologias.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfPatologiasFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 12;
        jPanel4.add(jtfPatologias, gridBagConstraints);

        jLabel24.setText("Gravidez: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 5;
        jPanel4.add(jLabel24, gridBagConstraints);

        jLabel21.setText("Tipo de Niño:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        jPanel4.add(jLabel21, gridBagConstraints);

        jcbTipoNiño.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hijo Donante", "Beneficiario" }));
        jcbTipoNiño.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbTipoNiñoItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 12;
        jPanel4.add(jcbTipoNiño, gridBagConstraints);

        jsGravidez.setModel(new javax.swing.SpinnerNumberModel(1, 0, 30, 1));
        jsGravidez.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsGravidezStateChanged(evt);
            }
        });
        jsGravidez.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jsGravidezFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        jPanel4.add(jsGravidez, gridBagConstraints);

        jlNombreEncargado.setFont(new java.awt.Font("Tahoma", 1, 11));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 13;
        jPanel4.add(jlNombreEncargado, gridBagConstraints);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondos/fondito3.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.gridheight = 11;
        jPanel4.add(jLabel25, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        jPanel5.add(jPanel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.gridheight = 12;
        jPanel1.add(jPanel5, gridBagConstraints);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bebé+enfermo (Custom).jpg"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 4, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 6;
        jPanel1.add(jLabel2, gridBagConstraints);

        jtPacientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"89-1", "Erick", "Cruz"}
            },
            new String [] {
                "Carnet", "Nombres", "Apellidos"
            }
        ));
        jtPacientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jtPacientes.setRowHeight(25);
        jScrollPane6.setViewportView(jtPacientes);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 14;
        jPanel1.add(jPanel10, gridBagConstraints);

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Lista Pacientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Salir");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1051)/2, (screenSize.height-587)/2, 1051, 587);
    }// </editor-fold>//GEN-END:initComponents

    private void jbAlmacenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlmacenarActionPerformed
        // TODO add your handling code here:
        try {
            if (jtfNombres.getText().equals("") || jtfApellidos.getText().equals("") || bgSexoNino.isSelected(null) || jtfTarjeta.getText().equals("") || jtfEncargado.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "¡Por favor, complete los datos del paciente!");
            } else {
                pte = new Paciente(carnet, nombre, apellido, fechaNa, sexo, semGes, Notas, tipo);
                propiedades = new PropiedadesPaciente(parto, edadMaterna, gravidez, patologias, municipio, departamento);
                opDN.almacenarInfoNino(pte, Encargado, propiedades);
            }
            opDN.listarNinos(jtPacientes);
            limpiarHabilitarValores();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jbAlmacenarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        limpiarHabilitarValores();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jrbMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMasculinoActionPerformed
        // TODO add your handling code here:
        this.sexo = "Masculino";
    }//GEN-LAST:event_jrbMasculinoActionPerformed

    private void jbReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReporteActionPerformed
        // TODO add your handling code here:
        opr.runReportePaciente("ConsultaPaciente", opr.getRuta(), this.jtfTarjeta.getText());
    }//GEN-LAST:event_jbReporteActionPerformed

    private void jbNuevaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevaConsultaActionPerformed
        // TODO add your handling code here:
        if (jtPacientes.getSelectedRow() == -1 || jtfNombres.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "¡Debe seleccionar un paciente,\ny abrir sus datos \npara la nueva consulta!");
        } else {
            jbNuevaConsulta.setEnabled(false);
            new Consult().setVisible(true);
            Consult.jlCarnet.setText(jtfTarjeta.getText());
            Date fec = new java.sql.Date(jcfechaNac.getDate().getTime());
            Consult.jlFechaNac.setText(fec.toString());
        }
    }//GEN-LAST:event_jbNuevaConsultaActionPerformed

    private void jbAgregarEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarEncargadoActionPerformed
        // TODO add your handling code here:
        new InstanceOfConsult().encargado.setVisible(true);
        AdministrarEncargado.jlIndiceOculto.setText("1");
        this.setVisible(false);
    }//GEN-LAST:event_jbAgregarEncargadoActionPerformed

    private void jbAbrirNinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAbrirNinoActionPerformed
        // TODO add your handling code here:
        try {
            if (this.jtPacientes.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(this, "¡Seleccione Niño!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                limpiarHabilitarValores();
                jtfTarjeta.setEditable(false);
                jbAlmacenar.setEnabled(false);
                jbCancelar.setEnabled(false);
                jbModificar.setEnabled(true);
                jbReporte.setEnabled(true);
                jbExcel.setEnabled(true);
                jbAgregarEncargado.setEnabled(false);
                Paciente paciente = new Paciente();
                PropiedadesPaciente propiedad = new PropiedadesPaciente();
                paciente = opDN.listarInfoNino(jtPacientes.getValueAt(jtPacientes.getSelectedRow(), 0).toString());
                propiedad = opDN.listarPropeNino(jtPacientes.getValueAt(jtPacientes.getSelectedRow(), 0).toString());
                String encar = opDN.EncargadoPaciente(jtPacientes.getValueAt(jtPacientes.getSelectedRow(), 0).toString());
                op.listarConsulta(jtConsultas, paciente.getCarnet());
                String nameEnca = op.getNombrePaciente(encar);

                if (paciente.getSexo().equals("Masculino")) {
                    jrbMasculino.setSelected(true);
                }
                if (paciente.getSexo().equals("Femenino")) {
                    jrbFemenino.setSelected(true);
                }
                Object arreglo[] = new Object[jcbPatologias.getItemCount()];
                for (int i = 0; i < jcbPatologias.getItemCount(); i++) {
                    arreglo[i] = jcbPatologias.getItemAt(i);
                }
                for (int i = 0; i < arreglo.length; i++) {
                    if (arreglo[i].equals(propiedad.getPatologia())) {
                        jcbPatologias.setSelectedItem(propiedad.getPatologia());
                        break;
                    } else {
                        jcbPatologias.setSelectedItem("Otras Patologías");
                        jtfPatologias.setText(propiedad.getPatologia());
                    }
                }
                jlNumeroConsultas.setText("" + jtConsultas.getRowCount());
                jtfTarjeta.setText(paciente.getCarnet());
                jtfNombres.setText(paciente.getNombre());
                jtfApellidos.setText(paciente.getApellido());
                jtfEncargado.setText(encar);
                jlNombreEncargado.setText(nameEnca);
                jcfechaNac.setDate(paciente.getFechaNac());
                jcbDepartamento.setSelectedItem(propiedad.getDepartamento());
                jcbMunicipio.setSelectedItem(propiedad.getMunicipio());
                jtfNotas.setText(paciente.getNotas());
                int grave = Integer.parseInt(propiedad.getGravidez());
                jsGravidez.setValue(grave);
                int val = Integer.parseInt(propiedad.getEdadMaterna());
                jsEdadMaterna.setValue(val);
                jcbParto.setSelectedItem(propiedad.getParto());
                jcbTipoNiño.setSelectedItem(paciente.getTipo());

                String sm = paciente.getSemGest();
                sm = sm.substring(0, 2);
                jsSemGestacion.setValue(Integer.parseInt(sm));


            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jbAbrirNinoActionPerformed

    private void jbNuevoNinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoNinoActionPerformed
        // TODO add your handling code here:
        limpiarHabilitarValores();
        DefaultTableModel model = new DefaultTableModel();
        jbAgregarEncargado.setEnabled(true);
        jtfTarjeta.setEditable(true);
        jbModificar.setEnabled(false);
        jbAlmacenar.setEnabled(true);
        jbReporte.setEnabled(false);
        jbExcel.setEnabled(false);
        jbCancelar.setEnabled(true);
        jtConsultas.setModel(model);
    }//GEN-LAST:event_jbNuevoNinoActionPerformed

    private void jbEliminarNinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarNinoActionPerformed
        // TODO add your handling code here:
        try {
            if (jtPacientes.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(rootPane, "Debe seleccionar el niño para eliminar su información");
            } else {
                int msj = JOptionPane.showConfirmDialog(rootPane, "¿En verdad desea eliminar la información del niño?", "Confirmación", JOptionPane.YES_NO_OPTION);
                if (msj == 0) {
                    if (opU.isAdmin()) {
                        String cart = jtPacientes.getValueAt(jtPacientes.getSelectedRow(), 0).toString();
                        usu = opU.usuarioUp();
                        opU.setEstado(usu, "El. paciente " + cart);
                        op.eliminarPropiedadPaciente(cart);
                        op.eliminarConsultas(cart);
                        opDN.eliminarNino(cart);
                        limpiarHabilitarValores();
                        DefaultTableModel model = (DefaultTableModel) jtPacientes.getModel();
                        model.removeRow(jtPacientes.getSelectedRow());
                        DefaultTableModel model2 = new DefaultTableModel();
                        jtConsultas.setModel(model2);

                    } else {
                        JOptionPane.showMessageDialog(null, "Lo siento, usted no esta autorizado para realizar esta acción\nsolo un administrador puede hacerlo", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jbEliminarNinoActionPerformed

    private void jbBuscarNinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarNinoActionPerformed
        // TODO add your handling code here:
        new InstanceOfConsult().buscar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbBuscarNinoActionPerformed

    private void jbExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcelActionPerformed
        // TODO add your handling code here:
        opx.exportarExcelCons(opi.obtenerRutaExcel(), jtConsultas);
    }//GEN-LAST:event_jbExcelActionPerformed

    private void jcfechaNacDateChanged(org.freixas.jcalendar.DateEvent evt) {//GEN-FIRST:event_jcfechaNacDateChanged
        // TODO add your handling code here:
        fechaNa = jcfechaNac.getDate();
        calcularEdad(fechaNa);
    }//GEN-LAST:event_jcfechaNacDateChanged

    private void jsSemGestacionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsSemGestacionStateChanged
        // TODO add your handling code here:
        this.semGes = jsSemGestacion.getValue().toString();
    }//GEN-LAST:event_jsSemGestacionStateChanged

    private void jtfEncargadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEncargadoFocusLost
        // TODO add your handling code here:
        ControlPaciente.Encargado = jtfEncargado.getText();
    }//GEN-LAST:event_jtfEncargadoFocusLost

    private void jtfNombresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNombresFocusLost
        // TODO add your handling code here:
        this.nombre = jtfNombres.getText();
    }//GEN-LAST:event_jtfNombresFocusLost

    private void jtfApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfApellidosFocusLost
        // TODO add your handling code here:
        this.apellido = jtfApellidos.getText();
    }//GEN-LAST:event_jtfApellidosFocusLost

    private void jrbFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFemeninoActionPerformed
        // TODO add your handling code here:
        this.sexo = "Femenino";
    }//GEN-LAST:event_jrbFemeninoActionPerformed

    private void jtfTarjetaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfTarjetaFocusLost
        // TODO add your handling code here:
        this.carnet = jtfTarjeta.getText();
    }//GEN-LAST:event_jtfTarjetaFocusLost

    private void jtfNotasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNotasFocusLost
        // TODO add your handling code here:
        this.Notas = jtfNotas.getText();
    }//GEN-LAST:event_jtfNotasFocusLost

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        new InstanceOf().actividad.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jcbDepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbDepartamentoItemStateChanged
        // TODO add your handling code here:
        calculos.Municipios(jcbDepartamento.getSelectedIndex(), jcbMunicipio);
        this.departamento = jcbDepartamento.getSelectedItem().toString();
    }//GEN-LAST:event_jcbDepartamentoItemStateChanged

    private void jcbPatologiasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbPatologiasItemStateChanged
        // TODO add your handling code here:
        if (jcbPatologias.getSelectedIndex() == 7) {
            jtfPatologias.setEnabled(true);
        } else {
            jtfPatologias.setEnabled(false);
            this.patologias = jcbPatologias.getSelectedItem().toString();
        }
    }//GEN-LAST:event_jcbPatologiasItemStateChanged

    private void jtfPatologiasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfPatologiasFocusLost
        // TODO add your handling code here:
        this.patologias = jtfPatologias.getText();
    }//GEN-LAST:event_jtfPatologiasFocusLost

    private void jbOtrosDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOtrosDatosActionPerformed
        // TODO add your handling code here

        if (jtPacientes.getSelectedRow() == -1 || !jtfTarjeta.getText().equals(jtPacientes.getValueAt(jtPacientes.getSelectedRow(), 0).toString())) {
            JOptionPane.showMessageDialog(rootPane, "¡Debe seleccionar un paciente \ny luego abrir sus datos!");
        } else {
            try {
                Date fecha = new java.sql.Date(jcfechaNac.getDate().getTime());
                OtrosDatos.carnet = jtPacientes.getValueAt(jtPacientes.getSelectedRow(), 0).toString();
                new OtrosDatos().setVisible(true);
                OtrosDatos.jlNombre.setText(jtPacientes.getValueAt(jtPacientes.getSelectedRow(), 1).toString() + " " + jtPacientes.getValueAt(jtPacientes.getSelectedRow(), 2).toString());
                OtrosDatos.jlCarnet.setText(jtPacientes.getValueAt(jtPacientes.getSelectedRow(), 0).toString());
                OtrosDatos.jlEdadInicio.setText(fecha.toString());
                int tamaño = jtConsultas.getRowCount();
                OtrosDatos.jtfPesoActual.setText(jtConsultas.getValueAt(tamaño - 1, 3).toString());
                OtrosDatos.jtfEstaturaActual.setText(jtConsultas.getValueAt(tamaño - 1, 4).toString());
                OtrosDatos.jtfPCefalicoActual.setText(jtConsultas.getValueAt(tamaño - 1, 5).toString());
                double racion = 0.0;
                for (int i = 0; i < tamaño; i++) {
                    racion = racion + Double.parseDouble(jtConsultas.getValueAt(i, 6).toString());
                }
                OtrosDatos.jtfRacionesAsignadas.setText("" + racion);
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }

        }
    }//GEN-LAST:event_jbOtrosDatosActionPerformed

    private void jbAbrirConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAbrirConsultaActionPerformed
        // TODO add your handling code here:
        if (jtConsultas.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(rootPane, "¡Seleccione la consulta a abrir!");
        } else {
            jbAbrirConsulta.setEnabled(false);
            InfoConsulta info = new InfoConsulta();
            info.setVisible(true);
            Consulta consulta;
            String jvmp = jtConsultas.getValueAt(jtConsultas.getSelectedRow(), 2).toString();
            String carnet = jtConsultas.getValueAt(jtConsultas.getSelectedRow(), 1).toString();
            String Notas = jtConsultas.getValueAt(jtConsultas.getSelectedRow(), 8).toString();
            double peso = Double.parseDouble(jtConsultas.getValueAt(jtConsultas.getSelectedRow(), 3).toString());
            double estatura = Double.parseDouble(jtConsultas.getValueAt(jtConsultas.getSelectedRow(), 4).toString());
            double pCefalico = Double.parseDouble(jtConsultas.getValueAt(jtConsultas.getSelectedRow(), 5).toString());
            String racion = jtConsultas.getValueAt(jtConsultas.getSelectedRow(), 6).toString();
            String condicionSalud;
            info.jtfMedico.setText(jvmp);
            info.jlCarnet.setText(carnet);
            Date fec = new java.sql.Date(jcfechaNac.getDate().getTime());
            info.jlFechaNac.setText(fec.toString());
            info.jlFechaConsulta.setText(jtConsultas.getValueAt(jtConsultas.getSelectedRow(), 0).toString());
            info.jtfDiagnostico.setText(Notas);
            info.jsPeso.setValue(peso);
            info.jsEstatura.setValue(estatura);
            info.jsPerimetroCefalico.setValue(pCefalico);
            info.jtfRacionAsignada.setText(racion);
            if (jtConsultas.getValueAt(jtConsultas.getSelectedRow(), 7).equals("Niño sano")) {
                info.jrbNiñoSano.setSelected(true);
                condicionSalud = "Niño sano";
            } else if (jtConsultas.getValueAt(jtConsultas.getSelectedRow(), 7).equals("IRA")) {
                info.jrbIRA.setSelected(true);
                condicionSalud = "IRA";
            } else if (jtConsultas.getValueAt(jtConsultas.getSelectedRow(), 7).equals("EDA")) {
                info.jrbEDA.setSelected(true);
                condicionSalud = "EDA";
            } else {
                info.jrbOtra.setSelected(true);
                condicionSalud = jtConsultas.getValueAt(jtConsultas.getSelectedRow(), 7).toString();
                info.jtfOtraEnfermedad.setText(condicionSalud);
            }
            consulta = new Consulta(null, carnet, peso, estatura, String.valueOf(pCefalico), Integer.parseInt(jvmp), condicionSalud, Double.parseDouble(racion), Notas);
            info.ori = consulta;
            

        }
    }//GEN-LAST:event_jbAbrirConsultaActionPerformed

    private void jcbPartoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbPartoItemStateChanged
        // TODO add your handling code here:
        this.parto = jcbParto.getSelectedItem().toString();
    }//GEN-LAST:event_jcbPartoItemStateChanged

    private void jsEdadMaternaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsEdadMaternaStateChanged
        // TODO add your handling code here:
        this.edadMaterna = jsEdadMaterna.getValue().toString();
    }//GEN-LAST:event_jsEdadMaternaStateChanged

    private void jcbMunicipioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbMunicipioItemStateChanged
        // TODO add your handling code here:
        this.municipio = jcbMunicipio.getSelectedItem().toString();
    }//GEN-LAST:event_jcbMunicipioItemStateChanged

    private void jbEliminarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarConsultaActionPerformed
        // TODO add your handling code here:
        if (jtConsultas.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(rootPane, "¡Seleccione la Consulta a Eliminar!");
        } else {
            int msj = JOptionPane.showConfirmDialog(rootPane, "¿En verdad desea eliminar la información de la consulta?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (msj == 0) {
                if (opU.isAdmin()) {
                    usu = opU.usuarioUp();
                    opU.setEstado(usu, "El. fchCons: " + jtConsultas.getValueAt(jtConsultas.getSelectedRow(), 0).toString() + "carnetP: " + jtConsultas.getValueAt(jtConsultas.getSelectedRow(), 1).toString());
                    op.eliminarConsulta(jtConsultas.getValueAt(jtConsultas.getSelectedRow(), 1).toString(), jtConsultas.getValueAt(jtConsultas.getSelectedRow(), 0).toString(), jtConsultas.getValueAt(jtConsultas.getSelectedRow(), 2).toString(), jtConsultas.getValueAt(jtConsultas.getSelectedRow(), 3).toString(), jtConsultas.getValueAt(jtConsultas.getSelectedRow(), 4).toString(), jtConsultas.getValueAt(jtConsultas.getSelectedRow(), 5).toString());
                    DefaultTableModel model = (DefaultTableModel) jtConsultas.getModel();
                    model.removeRow(jtConsultas.getSelectedRow());
                    int dato = Integer.parseInt(jlNumeroConsultas.getText());
                    dato = (dato - 1);
                    jlNumeroConsultas.setText("" + dato);
                } else {
                    JOptionPane.showMessageDialog(null, "Lo siento, usted no esta autorizado para realizar esta acción\nsolo un administrador puede hacerlo", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jbEliminarConsultaActionPerformed

    private void jbBuscarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarConsultaActionPerformed
        // TODO add your handling code here:
        if (jtPacientes.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(rootPane, "¡Debe abrir un paciente!");
        } else {
            if (jcbSeleccionarBusquedaConsulta.getSelectedIndex() == 0) {
                op.listarConsulta(jtConsultas, jtPacientes.getValueAt(jtPacientes.getSelectedRow(), 0).toString());
                jtfPalabraBuscar.setText("");
            } else if (jcbSeleccionarBusquedaConsulta.getSelectedIndex() == 1) {
                op.BuscarConsulta(jtConsultas, "FechaHora", value, jtPacientes.getValueAt(jtPacientes.getSelectedRow(), 0).toString());
                jtfPalabraBuscar.setText("");
            } else if (jcbSeleccionarBusquedaConsulta.getSelectedIndex() == 2) {
                op.BuscarConsulta(jtConsultas, "JVPM", value, jtPacientes.getValueAt(jtPacientes.getSelectedRow(), 0).toString());
                jtfPalabraBuscar.setText("");
            }
        }

    }//GEN-LAST:event_jbBuscarConsultaActionPerformed

    private void jtfPalabraBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfPalabraBuscarFocusLost
        // TODO add your handling code here:
        value = jtfPalabraBuscar.getText();
    }//GEN-LAST:event_jtfPalabraBuscarFocusLost

    private void jcbTipoNiñoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbTipoNiñoItemStateChanged
        // TODO add your handling code here:
        this.tipo = jcbTipoNiño.getSelectedItem().toString();
    }//GEN-LAST:event_jcbTipoNiñoItemStateChanged

    private void jsGravidezFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jsGravidezFocusLost
        // TODO add your handling code here
        gravidez = jsGravidez.getValue().toString();
    }//GEN-LAST:event_jsGravidezFocusLost

    private void jsGravidezStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsGravidezStateChanged
        // TODO add your handling code here:
        gravidez = jsGravidez.getValue().toString();
    }//GEN-LAST:event_jsGravidezStateChanged

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // TODO add your handling code here:
        try {
            carnet = jtfTarjeta.getText();
            nombre = jtfNombres.getText();
            apellido = jtfApellidos.getText();
            fechaNa = jcfechaNac.getDate();
            if (jrbMasculino.isSelected() == true) {
                sexo = "Masculino";
            } else if (jrbFemenino.isSelected() == true) {
                sexo = "Femenino";
            }
            semGes = jsSemGestacion.getValue().toString();
            Notas = jtfNotas.getText();
            tipo = jcbTipoNiño.getSelectedItem().toString();
            parto = jcbParto.getSelectedItem().toString();
            edadMaterna = jsEdadMaterna.getValue().toString();
            gravidez = jsGravidez.getValue().toString();
            patologias = jcbPatologias.getSelectedItem().toString();
            municipio = jcbMunicipio.getSelectedItem().toString();
            departamento = jcbDepartamento.getSelectedItem().toString();

            usu = opU.usuarioUp();
            opU.setEstado(usu, "Modf. Paciente crnt:" + carnet);

            pte = new Paciente(carnet, nombre, apellido, fechaNa, sexo, semGes, Notas, tipo);
            propiedades = new PropiedadesPaciente(parto, edadMaterna, gravidez, patologias, municipio, departamento);
            opDN.actualizarPaciente(pte, propiedades);
            int row = jtPacientes.getSelectedRow();
            opDN.listarNinos(jtPacientes);
            jtPacientes.setRowSelectionInterval(row, row);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "¡Error al Modificar!");
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jsSemGestacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jsSemGestacionFocusLost
        // TODO add your handling code here:
        this.semGes = jsSemGestacion.getValue().toString();
    }//GEN-LAST:event_jsSemGestacionFocusLost

    private void jsEdadMaternaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jsEdadMaternaFocusLost
        // TODO add your handling code here:
        this.edadMaterna = jsEdadMaterna.getValue().toString();
    }//GEN-LAST:event_jsEdadMaternaFocusLost

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new ListaPacientes().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ControlPaciente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexoNino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public static javax.swing.JButton jbAbrirConsulta;
    private javax.swing.JButton jbAbrirNino;
    private javax.swing.JButton jbAgregarEncargado;
    private javax.swing.JButton jbAlmacenar;
    private javax.swing.JButton jbBuscarConsulta;
    private javax.swing.JButton jbBuscarNino;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEliminarConsulta;
    private javax.swing.JButton jbEliminarNino;
    private javax.swing.JButton jbExcel;
    private javax.swing.JButton jbModificar;
    public static javax.swing.JButton jbNuevaConsulta;
    private javax.swing.JButton jbNuevoNino;
    private javax.swing.JButton jbOtrosDatos;
    private javax.swing.JButton jbReporte;
    private javax.swing.JComboBox jcbDepartamento;
    private javax.swing.JComboBox jcbMunicipio;
    private javax.swing.JComboBox jcbParto;
    private javax.swing.JComboBox jcbPatologias;
    private javax.swing.JComboBox jcbSeleccionarBusquedaConsulta;
    private javax.swing.JComboBox jcbTipoNiño;
    private org.freixas.jcalendar.JCalendarCombo jcfechaNac;
    public static javax.swing.JLabel jlEdad;
    public static javax.swing.JLabel jlNombreEncargado;
    public static javax.swing.JLabel jlNumeroConsultas;
    private javax.swing.JRadioButton jrbFemenino;
    private javax.swing.JRadioButton jrbMasculino;
    private javax.swing.JSpinner jsEdadMaterna;
    private javax.swing.JSpinner jsGravidez;
    private javax.swing.JSpinner jsSemGestacion;
    public static javax.swing.JTable jtConsultas;
    public static javax.swing.JTable jtPacientes;
    private javax.swing.JTextField jtfApellidos;
    public volatile javax.swing.JTextField jtfEncargado;
    private javax.swing.JTextField jtfNombres;
    private javax.swing.JEditorPane jtfNotas;
    private javax.swing.JTextField jtfPalabraBuscar;
    private javax.swing.JTextField jtfPatologias;
    private javax.swing.JTextField jtfTarjeta;
    // End of variables declaration//GEN-END:variables
}
