/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InformeProduccion.java
 *
 * Created on 09-26-2012, 12:21:29 AM
 */
package vistas;

import Operaciones.OperacionesExcel;
import Operaciones.OperacionesInformes;
import Operaciones.OperacionesReportes;
import accesoDatos.Operaciones;
import Instancia.InstanceOf;
import accesoDatos.OperacionesUsuarios;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.write.WriteException;

/**
 *
 * @author Erick Cruz
 */
public class InformeProduccion extends javax.swing.JFrame {

    /** Creates new form InformeProduccion */
    Operaciones op = new Operaciones();
    OperacionesUsuarios opU = new OperacionesUsuarios();
    OperacionesExcel opx = new OperacionesExcel();
    OperacionesReportes opr = new OperacionesReportes();
    OperacionesInformes opi = new OperacionesInformes();
    String usu;
    public int filaAnterior = 0;
    RutaRecDomiciliar recoleccion = new RutaRecDomiciliar();

    public InformeProduccion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        opi.listarInformeProd(jtInforme);
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/iconBLH.png"));
        return retValue;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtInforme = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jbNuevoInforme1 = new javax.swing.JButton();
        jbModificar1 = new javax.swing.JButton();
        jbEliminar1 = new javax.swing.JButton();
        jbCancelar1 = new javax.swing.JButton();
        jbExcel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informe de Produccion");
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(997, 522));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(142, 180, 227));
        jPanel1.setMaximumSize(new java.awt.Dimension(701, 505));
        jPanel1.setMinimumSize(new java.awt.Dimension(701, 505));

        jtInforme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "At. Individual", "At. Grupal", "Vis. Domiciliar", "Total Aten.", "Recolectado (lt)", "Distribuido (lt)", "Donantes", "Receptores", "Microbiologicos", "Fisico-Quimicas", "Crematocito", "Acidez Dornic", "Total Ana FQ", "Total General"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtInforme.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtInforme.setAutoscrolls(false);
        jtInforme.setRowHeight(25);
        jScrollPane1.setViewportView(jtInforme);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prodLeche.jpg"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));

        jPanel3.setBackground(new java.awt.Color(142, 180, 227));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 102))); // NOI18N
        net.java.dev.koalalayout.KoalaLayout koalaLayout2 = new net.java.dev.koalalayout.KoalaLayout();
        koalaLayout2.setGridheight(16);
        koalaLayout2.setGridwidth(16);
        jPanel3.setLayout(koalaLayout2);

        jbNuevoInforme1.setFont(new java.awt.Font("Tahoma", 1, 16));
        jbNuevoInforme1.setText("Nuevo");
        jbNuevoInforme1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoInforme1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 2;
        jPanel3.add(jbNuevoInforme1, gridBagConstraints);

        jbModificar1.setFont(new java.awt.Font("Tahoma", 1, 16));
        jbModificar1.setText("Guardar");
        jbModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificar1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 2;
        jPanel3.add(jbModificar1, gridBagConstraints);

        jbEliminar1.setFont(new java.awt.Font("Tahoma", 1, 16));
        jbEliminar1.setText("Eliminar");
        jbEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminar1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 2;
        jPanel3.add(jbEliminar1, gridBagConstraints);

        jbCancelar1.setFont(new java.awt.Font("Tahoma", 1, 16));
        jbCancelar1.setText("Cancelar");
        jbCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelar1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 2;
        jPanel3.add(jbCancelar1, gridBagConstraints);

        jbExcel.setFont(new java.awt.Font("Tahoma", 1, 16));
        jbExcel.setText("Excel");
        jbExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 2;
        jPanel3.add(jbExcel, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("2012-03-22");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Ejemplo de fecha:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(142, 142, 142)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.setVisible(false);
        new InstanceOf().actividad.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new InstanceOf().actividad.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jbNuevoInforme1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoInforme1ActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel model = (DefaultTableModel) jtInforme.getModel();
            Object fila[] = {"", "", "", "", "", "", "", "", "", "", "", "", "", ""};
            model.addRow(fila);
            this.jbNuevoInforme1.setEnabled(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jbNuevoInforme1ActionPerformed

    private void jbModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificar1ActionPerformed
        // TODO add your handling code here:
        try {
            if (jtInforme.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(rootPane, "¡Seleccione Informe a Almacenar!");
            } else if (jtInforme.getValueAt(jtInforme.getSelectedRow(), 0).equals("") || jtInforme.getValueAt(jtInforme.getSelectedRow(), 1).equals("") || jtInforme.getValueAt(jtInforme.getSelectedRow(), 2).equals("") || jtInforme.getValueAt(jtInforme.getSelectedRow(), 3).equals("") || jtInforme.getValueAt(jtInforme.getSelectedRow(), 4).equals("") || jtInforme.getValueAt(jtInforme.getSelectedRow(), 5).equals("")) {
                JOptionPane.showMessageDialog(rootPane, "¡Por favor, complete datos del Informe!");
            } else {
                clases.InformeProduccion inf = new clases.InformeProduccion(jtInforme.getValueAt(jtInforme.getSelectedRow(), 0).toString(), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 1).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 2).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 3).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 4).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 5).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 6).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 7).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 8).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 9).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 10).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 11).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 12).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 13).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 14).toString()));
                opi.almacenarInformeProd(inf);
                this.jbNuevoInforme1.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al almacenar: " + e.getMessage());
        }
    }//GEN-LAST:event_jbModificar1ActionPerformed

    private void jbEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminar1ActionPerformed
        // TODO add your handling code here:
        try {
            if (jtInforme.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(rootPane, "¡Seleccione Informe a Eliminar!");
            } else {
                int msj = JOptionPane.showConfirmDialog(rootPane, "¿En verdad desea eliminar?", "Confirmación", JOptionPane.YES_NO_OPTION);
                if (msj == 0) {
                    if (opU.isAdmin()) {
                        usu = opU.usuarioUp();
                        opU.setEstado(usu, "El. Inf.Prod.Fecha: " + jtInforme.getValueAt(jtInforme.getSelectedRow(), 0).toString());
                        clases.InformeProduccion inf = new clases.InformeProduccion(jtInforme.getValueAt(jtInforme.getSelectedRow(), 0).toString(), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 1).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 2).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 3).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 4).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 5).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 6).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 7).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 8).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 9).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 10).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 11).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 12).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 13).toString()), Integer.parseInt(jtInforme.getValueAt(jtInforme.getSelectedRow(), 14).toString()));
                        opi.eliminarInformeProd(inf);
                        DefaultTableModel model = (DefaultTableModel) jtInforme.getModel();
                        model.removeRow(jtInforme.getSelectedRow());
                    } else {
                        JOptionPane.showMessageDialog(null, "Lo siento, usted no esta autorizado para realizar esta acción\nsolo un administrador puede hacerlo", "Error", JOptionPane.ERROR_MESSAGE);
                    }

                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jbEliminar1ActionPerformed

    private void jbCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelar1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new InstanceOf().actividad.setVisible(true);
    }//GEN-LAST:event_jbCancelar1ActionPerformed

    private void jbExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcelActionPerformed
        // TODO add your handling code here:
        try {
            opx.exportarExcelProd(opi.obtenerRutaExcel(), jtInforme);
        } catch (IOException ex) {
            Logger.getLogger(ControlPaciente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (WriteException ex) {
            Logger.getLogger(ControlPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformeProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformeProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformeProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformeProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new InformeProduccion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancelar1;
    private javax.swing.JButton jbEliminar1;
    private javax.swing.JButton jbExcel;
    private javax.swing.JButton jbModificar1;
    private javax.swing.JButton jbNuevoInforme1;
    private javax.swing.JTable jtInforme;
    // End of variables declaration//GEN-END:variables
}
